### ISSUE TITLE
Código: Vista de historias de vida, revisión vídeos terapeutas

### ISSUE THREAD

**Issue by erosguerrero** [NILGroup/TFG-22-23-Recuerdame2.0#100]
- [x] Filtro Apto/No Apto
- [x] Mostrar la fecha de fin (que es la actual)
- [x] Enderezar las columnas :D
- [x] En su PDF, la fecha más a la derecha, grisáceo, y con la Hora
- [x] Espacios entre fotos cuidao [29]
- [x] Arreglar un poco las fotos (orden y tamaño)
- [x] Arreglar multifiltro
- [x] Adecuación de las imágenes al carrusell

**Comment by crisselene** [comment]
Las imágenes están hechas con las fotos de prueba, no con las de multimedia

**Comment by crisselene** [comment]
actualización: ya está hecho con las imágenes de multimedia y si no tiene foto de perfil se pone la de hombre si es un hombre y en otro caso la de mujer

**Comment by crisselene** [comment]
![Image](https://user-images.githubusercontent.com/35759827/218137103-5b1bdad3-2254-4b2e-9f11-ac13b401ce38.png)

**Comment by crisselene** [comment]
hecho, queda pendiente de si las queremos más grandes, pequeñas... etc
