### ISSUE TITLE
Código: Vista Paciente, revisión vídeo terapeutas

### ISSUE THREAD

**Issue by erosguerrero** [NILGroup/TFG-22-23-Recuerdame2.0#103]
- [x] Botón Otro
- [x] Foto del paciente en la vista de show
- [x] Ordenar por fecha los diagnósticos
- [x] Antigüedad si está en residencia

**Comment by Lurngi** [comment]
Hay que hablar lo del diagnostico principal

**Comment by crisselene** [comment]
**Esto creo que es un tema aparte** pero creo que cuando el terapeuta ve un paciente y luego vuelve a la losta de pacientes y crea uno nuevo, tal vez no debería aparecer ningún paciente en la navbar:


![Image](https://user-images.githubusercontent.com/35759827/215345101-88e8ee94-103d-4388-a816-e54ae09513eb.png)



![Image](https://user-images.githubusercontent.com/35759827/215345123-75be8bfe-5391-445d-92f0-e9ff1233f679.png)

**Comment by crisselene** [comment]
yo creo un nuevo paciente que vive en una residencia: 


![Image](https://user-images.githubusercontent.com/35759827/215345215-c8318385-ea15-46f1-82c3-e83e948b6328.png)

pero luego en su perfil la fecha de inscripción en la residencia NO APARECE:


![Image](https://user-images.githubusercontent.com/35759827/215345246-351975ba-76e4-4e77-9e05-60f9868a7257.png)

**Comment by PabloMartinez01** [comment]
Lo mismo que el comentario anterior, no se guarda la fecha de inscripción en la base de datos

**Comment by Lurngi** [comment]
Corregido

**Comment by crisselene** [comment]
like, pero no sé qué son los diagnósticos y dónde están xdd he entendido que son los informes de seguimiento?

**Comment by PabloMartinez01** [comment]
![Image](https://user-images.githubusercontent.com/95294905/220714502-8da93bae-c426-4d19-be10-74ad7be1b6ab.png)

Falta darle estilo al especifique. Todo lo demás bien, te doy like, pero cambia eso. Sucede en todas las vistas: crear, ver...
