### ISSUE TITLE
Código: Informe sesión, revisión vídeo terapeutas

### ISSUE THREAD

**Issue by erosguerrero** [NILGroup/TFG-22-23-Recuerdame2.0#104]
- [x] Eliminar el botón de apto del informe de sesión
- [x] Lista de Recuerdos utilizados, y poder marcarlos como aptos o no aptos, modificar su puntuación y etiqueta [24]
- [x] Fecha no carga
- [x] Añadir duración
- [x] Quitar fecha fin. (Referente a la tabla)
- [x] Cambiar nombre de fecha de informe a fecha fin (No sé a qué se refiere, probablemente algo eliminado tras la reunión)

**Comment by erosguerrero** [comment]
Falta la lista de recuerdos (?

**Comment by Lurngi** [comment]
Se encuentran dentro de la sesión. En el informe diría que solo deberían aparecer, con posibilidad de editarlos, al cerrar o editarlo, no al verlo, ya que no tienen relevancia para el mismo y el poder modificarlos es solo una facilidad de cara a los terapeutas para hacer los ajustes necesarios tras la sesión. 

De todas formas se puede preguntar si no te convence la respuesta
