### ISSUE TITLE
Memoria: Correción apartado 4, 4.1, 4.1.1, 4.1.1.1 y 4.1.2

### ISSUE THREAD

**Issue by erosguerrero** [NILGroup/TFG-22-23-Recuerdame2.0#108]

**Comment by crisselene** [comment]
En la corrección del apartado 4.1.3.1. se especifica que hay que añadir en las políticas explícitas que se trabaja sobre la rama Develop, he añadido este punto a la enumeración de las políticas del punto 4.1.2 :

- Se trabajará sobre la rama _Develop_ del proyecto en Github para poder realizar las pruebas necesarias. Tras cada entrega parcial  y estable del proyecto se subirán los cambios a la rama _Main_.

**Comment by SerArias** [comment]
Corregido el formato de la imagen de las políticas explícitas. Todos los cambios mencionados por Virginia están incorporados.
