### ISSUE TITLE
Código: reajustar tamaños de las columnas

### ISSUE THREAD

**Issue by crisselene** [NILGroup/TFG-22-23-Recuerdame2.0#125]
Queremos intentar reducir el tamaño de las tablas, para ello vamos a intentar ajustar los tamaños de las columnas. Aquellas que siempre tengan un tamaño fijo (como la fecha, que son siempre 10 caracteres) se les puede hacer un "fit-content". Las que puedan cambiar de tamaño habrá que estudiar qué tamaño se estipula.

**Comment by erosguerrero** [comment]
![Image](https://user-images.githubusercontent.com/94256335/215518308-81dc7468-c699-4926-8f44-9495a4e8403b.png)

**Comment by erosguerrero** [comment]
En las tablas ajustadas el buscador se corta



![Image](https://user-images.githubusercontent.com/94256335/216005732-4add2ca8-42fe-4ba2-be4a-853263ce07df.png)

**Comment by Lurngi** [comment]
Ya no es problema porque se ha cambiado el buscador

**Comment by Lurngi** [comment]
Hacer más grande la columna de "Parentesco" y ponerle el nombre "Grado de parentesco" y disminuir el tamaño de los botones

![Image](https://user-images.githubusercontent.com/72133257/216768203-26b501f0-4c7d-440f-ba2b-80eaa7fb5254.png)

**Comment by Lurngi** [comment]
Disminuir el tamaño de la columna del numero de sesiones (Le he cambiado el nombre para que sea más pequeñito) y aumentar el de la columna de "Diagnóstico"

![Image](https://user-images.githubusercontent.com/72133257/216769182-fc25663a-86c9-4c7c-9424-671bdac27187.png)
