### ISSUE TITLE
Código: Rediseño tabla informes

### ISSUE THREAD

**Issue by crisselene** [NILGroup/TFG-22-23-Recuerdame2.0#126]
Se puede finalizar una sesión y acabar el informe a posteriori. 
Dos estados: abierto (puedo finalizar) y cerrado (finalizado)

Cambiar el botón de ver pdf al final de la fila.

Rediseño de la tabla en la imagen:

![Image](https://user-images.githubusercontent.com/35759827/208070459-4fbf2e60-b4b7-4051-8153-f5ba40908cda.png)

**Comment by crisselene** [comment]
cambio de disposición tabla sesiones

**Comment by Lurngi** [comment]
No me termina de convencer que el botón de cerrar/generar informe esté junto a los iconos. Sé que lo pidieron pero yo lo rediscutiría
