### ISSUE TITLE
Código: Informe de sesión cambiar el nombre

### ISSUE THREAD

**Issue by crisselene** [NILGroup/TFG-22-23-Recuerdame2.0#130]
quitar el id y poner la fecha
En vez de informe 1, que sea informe 22-03-2013

**Comment by Lurngi** [comment]
Hecho, pero queda una tabla muy fea con solo 2 columnas, revaloraría con Virginia y Susana la utilidad de esta vista, sobre todo pudiendo implementar su funcionalidad facilmente en la del listado de sesiones
