### ISSUE TITLE
Código: Rediseño historia de vida

### ISSUE THREAD

**Issue by crisselene** [NILGroup/TFG-22-23-Recuerdame2.0#131]
- [x] Cambiar selección en etiquetas.
- [x] Que se vean los checkbox sin desplegable.
- [x] cambiar la selección de recuerdos aptos y/o no aptos

**Comment by Lurngi** [comment]
Me parecen muy feos los checkbox. Aunque fue lo que nos pidieron Virginia y Susana. De momento like, queda que lo valoren ellas
