### ISSUE TITLE
Código: filtros en las tablas

### ISSUE THREAD

**Issue by crisselene** [NILGroup/TFG-22-23-Recuerdame2.0#132]
Filtro en todo. Investigar filtro (igual JQUERY).

**Comment by crisselene** [comment]
aparece esto cuando visualizo una sesión y le doy a editar un recuerdo
![Image](https://user-images.githubusercontent.com/35759827/215340967-01d41fcd-dcd8-4872-a0c1-ea11c42a4751.png)

**Comment by crisselene** [comment]
también sucede en ver perfil del paciente

![Image](https://user-images.githubusercontent.com/35759827/215342090-7dda0117-2ebc-4d0e-9e51-4f951f936a9b.png)

**Comment by crisselene** [comment]
Además, en crear nueva sesión el estilo de la tabla queda un poco raro y parece que se corta:

![Image](https://user-images.githubusercontent.com/35759827/215342958-2f115040-db2e-4771-a69c-a89797a59463.png)

**Comment by Lurngi** [comment]
Creo que está corregido todo

**Comment by Lurngi** [comment]
Los antiguos buscadores daban muchos problemas, así que los he refactorizado por completo. Los fallos que puedan tener referentes a las vistas de crear y editar entidades en principio se deben a la incorrecta inserción o eliminación de elementos en dicha tabla (en los scripts) y creo que es necesaria la creación de una tarea para dicha corrección

**Comment by crisselene** [comment]
cuando haces una búsqueda de algo que no existe (por ejemplo pongo skjdhsahs en la búsqueda) y cambias el filtro SIN BORRAR lo que has escrito, luego aunque lo borres y pongas otra cosa sigue mostrando que no hay resultados, hay que refrescar para poder verlo. es un bug algo tonto que yo creo que es muy minucioso, por tanto de momento doy mi llike

por ejemplo aquí hago una búsqueda sin sentido y me sale que no hay resultados:
![Image](https://user-images.githubusercontent.com/35759827/216775328-492c5e39-0aca-4eae-a351-b81dae1eed8b.png)

y depués cambio el filtro a fecha y borro la búsqueda y sigue sin aparecerme ningún resultado.

![Image](https://user-images.githubusercontent.com/35759827/216775354-b0710a75-d2c5-405d-9aac-f430abeaaf06.png)

**Comment by Lurngi** [comment]
Corregido
