### ISSUE TITLE
Código: persona relacionada y en cuidadores, apellido y nombre junto

### ISSUE THREAD

**Issue by crisselene** [NILGroup/TFG-22-23-Recuerdame2.0#133]
- [x] PERSONA RELACIONADA
- [x] CUIDADORES

**Comment by Lurngi** [comment]
No habría que hacerlo tambien con Paciente?

**Comment by crisselene** [comment]
creo que para los pacientes puede ser útil tener por separado por los apellidos ya que muchos terapeutas igual relacionan a sus pacientes por el apellido más que por el nombre?
