### ISSUE TITLE
Código: quitar alerts y poner ventanas emergentes

### ISSUE THREAD

**Issue by crisselene** [NILGroup/TFG-22-23-Recuerdame2.0#134]

**Comment by crisselene** [comment]
Quiero destacar que las ventanas emergentes de eliminar recuerdos son una monada y súper bien diseñaditas, muy buen trabajo!!!! 🥇

**Comment by SerArias** [comment]
Las ventanas emergentes de eliminar están implementadas en todas las entidades, a excepción de calendario. Como ya está contemplado dentro de la tarea de calendario, dejo mi like.
