### ISSUE TITLE
Código: Comprobar y modificar redirecciones

### ISSUE THREAD

**Issue by crisselene** [NILGroup/TFG-22-23-Recuerdame2.0#138]
Por ejemplo en cuidador:
- Al borrar está bien.
- Al crearlo te lleva al listado de paciente, y eso está mal. Lleva a la lista de cuidador.

**Comment by Lurngi** [comment]
En principio están todas estandarizadas, aunque son muchas y es posible que se me haya pasado alguna

**Comment by crisselene** [comment]
si edito un informe de seguimiento que ya estaba creado y le doy a finalizar me sale esto:


![Image](https://user-images.githubusercontent.com/35759827/216773957-a68e2fb9-5e16-4b08-a26a-db325b17cf19.png)

**Comment by Lurngi** [comment]
Justo esa ruta no la he tocado. De todas formas ya está arreglado, cosas del dropzone

**Comment by crisselene** [comment]
en recuerdo, cuando lo editas y das a finalizar te lleva a la vista de showRecuerdo en vez de al listado de recuerdos. En otras entidades no sucede así, por tanto no sé si es mejor dejarlo así o cambiarlo

**Comment by Lurngi** [comment]
Arreglado

**Comment by crisselene** [comment]
de cancelar edición de informe de sesión te lleva a listado de sesiones, no de informes de sesiones

**Comment by Lurngi** [comment]
De momento lo dejo así, pendiente de hablar con Virginia y Susana lo de la vista de informes de sesión

**Comment by erosguerrero** [comment]
Al borrar un recuerdo redirije a show

**Comment by erosguerrero** [comment]
Al borrar una sesión también

**Comment by Lurngi** [comment]
Corregido, era un pequeño problema del script

**Comment by crisselene** [comment]
cancelar de crear cuidador redirige a crear cuidador xdddd

![Image](https://user-images.githubusercontent.com/35759827/218126681-fdbca077-a7b4-4935-9dc8-a22b4382f813.png)

**Comment by Lurngi** [comment]
Corregido

**Comment by SerArias** [comment]
He estado revisando los redireccionamientos y creo que todas funcionan bien, espero no haberme saltado ninguna... Por mi parte, dejo like.
