### ISSUE TITLE
Código: se deben poder editar los cuidadores

### ISSUE THREAD

**Issue by crisselene** [NILGroup/TFG-22-23-Recuerdame2.0#139]

**Comment by Lurngi** [comment]
He creado todas las vistas correspondientes a los cuidadores. Queda pendiente la parte relacionada a multimedia, para lo que primero habrá que hablar con Virginia y Susana

**Comment by PabloMartinez01** [comment]
El editar, en lugar de editar añade uno nuevo

**Comment by Lurngi** [comment]
Corregido
