### ISSUE TITLE
Memoria: Corrección apartado 4.1.3 Retrospectivas

### ISSUE THREAD

**Issue by Lurngi** [NILGroup/TFG-22-23-Recuerdame2.0#148]

**Comment by crisselene** [comment]
En la corrección del apartado 4.1.3.1. se especifica que hay que añadir en las políticas explícitas que se trabaja sobre la rama Develop, he añadido este punto a la enumeración de las políticas del punto 4.1.2 :

- Se trabajará sobre la rama _Develop_ del proyecto en Github para poder realizar las pruebas necesarias. Tras cada entrega parcial y estable del proyecto se subirán los cambios a la rama _Main_.
