### ISSUE TITLE
Código: Recuerdo (sin archivos)

### ISSUE THREAD

**Issue by Lurngi** [NILGroup/TFG-22-23-Recuerdame2.0#15]
- [x] RECUERDO CREAR
- [x] RECUERDO EDITAR
- [x] LISTA DE RECUERDOS POR PACIENTE
- [x] RECUERDO VER

**Comment by erosguerrero** [comment]
Ya están los diálogos para crear personas y añadir existentes

**Comment by crisselene** [comment]
falta el margen de la izquierda, está todo muy pegado cuando se ve un recuerdo
![Image](https://user-images.githubusercontent.com/35759827/198890136-e575868f-8de9-431b-8411-49d9a67631ab.png)

**Comment by crisselene** [comment]
cuando el recuerdo se pasa de ciertos caracteres , falla, habría que avisar cuál es el número máximo de caracteres o quitar esa limitación


![Image](https://user-images.githubusercontent.com/35759827/198897321-35a5f0ce-2738-46b8-b882-81a1780ba89d.png)

**Comment by Lurngi** [comment]
Al editar un recuerdo, en el modal de añadir personas relacionadas existentes no se marcan las personas que ya están en ese recuerdo

**Comment by Lurngi** [comment]
Problemas generales:
- Falta añadir placeholders.
- Las URL no están normalizadas. Debería ser tipo /pacientes/(id)/recuerdos/(idRecuerdo) y solo es así en la vista de ver por paciente

Vista crear:
 - El botón de atrás devuelve a la lista de pacientes en lugar de a la lista de los recuerdos del paciente (Creo que es el problema de que a veces te salte una excepción ya que al volver a la lista de pacientes te elimina los datos del paciente almacenados para la navbar).
- La fecha no es un input required.
- La tabla de personas relacionadas tiene una columna de más.
![Image](https://user-images.githubusercontent.com/72133257/200145966-0415f8dc-9408-43cd-95b7-2306e1e93d27.png)
- Al seleccionar una categoría, si se selecciona "Otro" debería mostrar un nuevo desplegable para escribir esa categoría (Copia lo de persona relacionada)

Vista editar:
- El campo descripción no muestra la descripción y no está disabled
- La barra de puntuación no se muestra bien y no está disabled
- Si clickas para ver una persona relacionada y luego pulsas el botón de atrás, al pulsar el botón de atrás en la vista del recuerdo se genera un bucle entre ambas vistas
- Sucede una excepción al eliminar pacientes debido a que se intentan duplicar los valores de la tabla intermedia personarelacionada_recuerdo
![Image](https://user-images.githubusercontent.com/72133257/200146611-ee170e07-8e85-416d-9eef-e10c8514980a.png)

**Comment by erosguerrero** [comment]
**Falta añadir placeholders.**
Ninguna vista de entidad tiene placeholders. Se maximiza la consistencia y se plantea un cambio general.

**Las URL no están normalizadas. Debería ser tipo /pacientes/(id)/recuerdos/(idRecuerdo) y solo es así en la vista de ver por paciente
Vista ShowByPaciente:**

La normalización de las rutas no es cuestión de esta tarea.

**Comment by Lurngi** [comment]
- Lo de los placeholders queda pentiente de comentarse en la siguiente reunión, ya que hay algunas vistas que lo tienen y otras que no, hay que decidir qué hacer para mejorar la consistencia
- La normalización de las rutas de Recuerdo **ES** cuestión de esta tarea, ya que se supone que es la tarea en la que se han creado y es un error de consistencia
- La columna extra no debería mostrarse si no tiene contenido, y es un error. Por mucho que en otras vistas sí sea necesaria, en la captura que yo he pasado no lo es y está vacía, por lo que no debería aparecer o debería contener datos
- Lo de la categoría "Otro" no era así en R1, y es algo que deberíamos hablar en la próxima reunión porque este mismo caso se da en Persona Relacionada y los terapeutas pidieron lo que he comentado. Tiene mucho sentido (y es más consistente) hacerlo así, ya que es muy probable que se olvidasen de ponerlo en la memoria de Recuerdame 1. Igualmente queda pendiente de hablarse, incluso de comentarlo con Virginia y Susana
- Lo de los campos disabled es error mio, es de la vista Show, donde se puede mover la barra de puntuación (cuyo diseño tampoco es consistente con respecto a las vistas de crear y editar) y escribir en el campo de Descripción
- En cuanto a la excepción, otra vez errata mia, perdón. Sucede al eliminar personas relacionadas de la tabla y enviar el formulario, salta la excepción mostrada anteriormente ya que no se modifica correctamente la tabla intermedia y se intenta insertar una relación ya existente

**Comment by erosguerrero** [comment]
1. Exacto
2. Es una cuestión que sigo recordando que quedó como pendiente y que no fue aprobada en ese momento. Sin embargo, como ya está hecha habrá que hacerla para el resto de vista. Insisto, el enrutado no **es** algo de esta tarea. Pues es funcional.
3. La columna, reitero, **es** necesaria y **nunca** estará vacía. Es una tarea pendiente de acabarse personas relacionadas con su nuevos atributos para poder actualizar el modal y por tanto esa columna. Que por si falta información, es la que contendrá el ojo que redirecciona a la persona en cuestión.
4. Más cosas para futura reunión.
5. Cosa de la refactorización y su nuevo sistema de disabled. Ya lo cambiaré.
6. Lo reviso.
