### ISSUE TITLE
Memoria: Introducción 5.2

### ISSUE THREAD

**Issue by erosguerrero** [NILGroup/TFG-22-23-Recuerdame2.0#150]
El apartado 5.2 ha sido movido, quitando de su interior el Rediseño. Ahora... no cuenta con introducción pues fue tachada en la corrección. Su validación esta pendiente, pero seguramente sea incorrecto dejarla sin introducción

![Image](https://user-images.githubusercontent.com/94256335/214099446-1ea520d6-f570-4175-b9ef-447df07d6bbb.png)

**Comment by Lurngi** [comment]
He escrito un par de lineas porque ya nos dijeron que no podía estar vacío

**Comment by crisselene** [comment]
hay una única línea, me parece algo escueto el apartado en sí. debería tal vez hacerse un brainstrom en alguna daily para ver qué más se puede añadir.

**Comment by Lurngi** [comment]
Lo he expandido un poco más, pero no sé qué más poner, creo que lo mejor sería comentarlo con Virginia y Susana, porque a mi parecer esa pequeña línea explica perfectamente el capítulo
