### ISSUE TITLE
Código: Validacion Formularios

### ISSUE THREAD

**Issue by PabloMartinez01** [NILGroup/TFG-22-23-Recuerdame2.0#152]
Cambiar la validación de los formularios

- [x] Paciente
- [x] Recuerdos
- [x] Modal Recuerdo (en sesión)
- [x] Sesión
- [x] PersonaRelacionada
- [x] Modal PersonaRelacionada (en recuerdo y en sesión)
- [x] Calendario
- [x] Cuidador

**Comment by crisselene** [comment]
todavía no está acabada la tarea, lo sé, pero lo pongo porque he encontrado este error por si se nos olvida:
a la hora de crear un paciente te deja que la fecha de nacimiento sea una a la que todavía no se ha llegado, por ejemplo 2030. Además la fecha de inscripción a la residencia le pasa igual.

**Comment by Lurngi** [comment]
La validación de números de telefono es demasiado rudimentaria. Deberían poder añadirse prefijos, guiones y cualquier formato de número de teléfono de cualquier país.
El regex para hacerlo bien (en principio) es el siguiente, para que ni tengas que buscarlo:

/^[\+]?[(]?[0-9]{3}[)]?[-\s\.]?[0-9]{3}[-\s\.]?[0-9]{4,6}$/im
