### ISSUE TITLE
Código: (?) en Vistas

### ISSUE THREAD

**Issue by erosguerrero** [NILGroup/TFG-22-23-Recuerdame2.0#158]
- [x] Recuerdo
- [x] Sesión
- [x] Historia de Vida: Generar
- [x] Persona relacionada
- [x] Informe de seguimiento

**Comment by Lurngi** [comment]
En mi opinión los simbolitos deberían estar completamente a la derecha de la label en todas las entidades, pero quizá es cuestión de gusto, yo lo comentaría con Virginia y Susana a ver qué opinan.

Tras eso, quedaría pendiente de valoración por parte de los terapeutas.

**Comment by Lurngi** [comment]
Los mensajes salen del label y no del icono de interrogación

**Comment by erosguerrero** [comment]
Corregido
