### ISSUE TITLE
Código: Imprimir los diagnósticos: Botón de imprimir

### ISSUE THREAD

**Issue by crisselene** [NILGroup/TFG-22-23-Recuerdame2.0#159]
Valorar si ponemos un botón de acceso rápido a la impresión. Valorarlo con las directoras de proyecto

**Comment by Lurngi** [comment]
He cambiado las redirecciones para unificarlas con el resto de las páginas. Ahora el hipervinculo redirige a la página del informe y he añadido un botón para ir directamente a la impresión (No imprime automaticamente), me gustaría feedback
