### ISSUE TITLE
Código: Sesión (Sin archivos)

### ISSUE THREAD

**Issue by Lurngi** [NILGroup/TFG-22-23-Recuerdame2.0#16]

**Comment by erosguerrero** [comment]
![Image](https://user-images.githubusercontent.com/94256335/198051421-e88e42fa-31b2-4447-855b-2a24df480342.png)

**Comment by crisselene** [comment]
botones small

**Comment by Lurngi** [comment]
Todo arreglado

**Comment by erosguerrero** [comment]
Al editar una sesión, en el modal de añadir recuerdos existentes no se marcan los recuerdos que ya están en esa sesión

**Comment by erosguerrero** [comment]
![Image](https://user-images.githubusercontent.com/94256335/200090025-cb3128e6-2d69-4d72-b626-c6ccd5131dc2.png)

El fondo no es Azul, supongo que porque todo está en un formulario de Clase Dropzone

**Comment by erosguerrero** [comment]
![Image](https://user-images.githubusercontent.com/94256335/200090059-9109b4cc-d22e-49c8-965f-d8706bd3cad4.png)

En este apartado de datos que iría?

**Comment by Lurngi** [comment]
Con una imagen tan pequeña no puedo identificar el apartado, necesito una captura dónde se vea toda la página y a poder ser la url

**Comment by erosguerrero** [comment]
Está en cualquier pantalla de sesión, ver editar crear... Al final del todo

**Comment by Lurngi** [comment]
Corregido

**Comment by Lurngi** [comment]
Es importante tener en cuenta que los modales quedan para el siguiente hito, ya que el modal de crear recuerdo debe poder abrir otro para crear una persona relacionada
