### ISSUE TITLE
Código: estilo vistas show

### ISSUE THREAD

**Issue by crisselene** [NILGroup/TFG-22-23-Recuerdame2.0#162]

**Comment by crisselene** [comment]
he puesto en negrita los nombres de los campos y centrado horizontalmente la información. Además, he procurado que las vistas sean responsive.

**Comment by PabloMartinez01** [comment]
![Image](https://user-images.githubusercontent.com/95294905/216832233-b01b2e9d-401f-4905-bac0-4811bd10f737.png)



![Image](https://user-images.githubusercontent.com/95294905/216832250-d21060ec-9776-4f23-9909-da7e5cc644dc.png)


Hay campos que no tienen el título en negrita (de normal están ocultos). Esto es en Crear Paciente

**Comment by Lurngi** [comment]
En algunas vistas, los show tienen el texto ligeramente descentrado hacia arriba en relación a la label

![Image](https://user-images.githubusercontent.com/72133257/217504098-9a2d35cf-9951-4e52-853d-2541c270bf5d.png)

**Comment by erosguerrero** [comment]
![Image](https://user-images.githubusercontent.com/94256335/218251954-4dbca9c9-9561-429a-aa08-a40108a2e48d.png)

Solo este campo se corta entre ? y texto

**Comment by crisselene** [comment]
corregido todo
