### ISSUE TITLE
Código: Tabla Recuerdo al crear (PRelacionadas) cortada

### ISSUE THREAD

**Issue by erosguerrero** [NILGroup/TFG-22-23-Recuerdame2.0#163]
No ocupa toda la pantalla

**Comment by PabloMartinez01** [comment]
SI. Ocupa toda la pantalla

**Comment by crisselene** [comment]
creando una sesión también se corta la tabla: 


![Image](https://user-images.githubusercontent.com/35759827/216774073-dda13396-b4ea-4102-9501-289aa89c8a6b.png)

**Comment by PabloMartinez01** [comment]
Corregido, faltaba darle width 100
