### ISSUE TITLE
Código: Añadir nuevos SweetAlert para la creación y edición

### ISSUE THREAD

**Issue by Lurngi** [NILGroup/TFG-22-23-Recuerdame2.0#164]

**Comment by erosguerrero** [comment]
Al editar sale "Creado satisfactoriamente" en vez de "Editado satisfactoriamente"

**Comment by Lurngi** [comment]
Corregido. Es cosa de las redirecciones. Si al editar se envía al showByPaciente va a poner el mensaje "creado" porque lo controla la vista y no el controller. Podríamos intentar cambiarlo pero es un lío y seguramente nos dé bastantes dolores de cabeza.

Por el momento las redirecciones están corregidas. Si vuelve a salir mal en alguna lo corrijo
