### ISSUE TITLE
Código: SweetAlert deshacer en eliminación

### ISSUE THREAD

**Issue by Lurngi** [NILGroup/TFG-22-23-Recuerdame2.0#165]

**Comment by crisselene** [comment]
cuando eliminas un recuerdo desde la vista de sesión, no te aparece la alerta de la eliminación y te lleva a la ventana de listado de recuerdos, donde efectivamente el recuerdo no aparece:

Por ejemplo, aquí elimino el recuerdo de entrada a la universidad:
![Image](https://user-images.githubusercontent.com/35759827/216774886-2a091433-5e8b-4f44-abf6-270855b581d4.png)


y me redirige y me muestra esto:
![Image](https://user-images.githubusercontent.com/35759827/216774879-63e8d62c-9395-422c-b1bf-2e128cc34463.png)

**Comment by Lurngi** [comment]
No debería poderse eliminar desde las vistas de show, hay que corregirlo

**Comment by erosguerrero** [comment]
Al eliminar un recuerdo me lleva a su show (???

**Comment by Lurngi** [comment]
Muevo a pendiente con fecha límite. Está el código comentado pero hay que retocarlo para que funcione bien y por el momento no es prioritario

**Comment by SerArias** [comment]
Me parece que el tiempo que aparece en pantalla el botón de deshacer es muy bajo (a mí al menos no me aparece más de un segundo). Creo que sería conveniente que apareciese, por ejemplo, 5 segundos.

**Comment by Lurngi** [comment]
Eso se debía a que el otro día corrigiendo un fallo se me olvidó dejarlo como estaba. Solucionado.

Tambien he mejorado la funcionalidad para que haga un borrado lógico que permita deshacer
