### ISSUE TITLE
Código: Personas relacionadas

### ISSUE THREAD

**Issue by Lurngi** [NILGroup/TFG-22-23-Recuerdame2.0#17]

**Comment by crisselene** [comment]
botones pequeños



![Image](https://user-images.githubusercontent.com/35759827/198020440-9815413d-bb4e-4c8d-b0bb-54ff25f09050.png)

**Comment by erosguerrero** [comment]
La parte baja tiene scroll, izquierda derecha, y no debería

**Comment by Lurngi** [comment]
- Faltan placeholders
- Se puede guardar una persona relacionada con un email con formato inválido
- El botón de eliminar de la vista de showByPaciente no pide confirmación antes de borrar

**Comment by PabloMartinez01** [comment]
- Corregido email
- Corregido confirmación antes de borrar
