### ISSUE TITLE
Código: Redimensionar inputs

### ISSUE THREAD

**Issue by Lurngi** [NILGroup/TFG-22-23-Recuerdame2.0#177]
Algunos inputs son demasiado pequeños y no se muestra el texto completo. Pasa sobre todo en los select de los modales, pero habría que redimensionar todo

**Comment by Lurngi** [comment]
- [ ] En sesión, estos 2 inputs tienen diferente tamaño y, en mi opinión, deberían estar a continuación de la label, no debajo
![Image](https://user-images.githubusercontent.com/72133257/220947549-65ef7c54-7897-43e3-b9ab-5f7b985e2631.png)


- [ ] En los modales sigue habiendo problemas porque la validación corta algunos campo (Igual habría que valorar mover el check fuera del input?)
- [ ] Los inputs de fecha y polaridad son más pequeños que el resto (También ocurre en la vista de recuerdo)
![Image](https://user-images.githubusercontent.com/72133257/220948074-6a00449e-b24d-42c0-9a9c-c8bfc7888fd0.png)


- [ ] En las evaluaciones (informe de seguimiento), este input creo que tenía una pequeña separación con la barra, aunque no estoy seguro
![Image](https://user-images.githubusercontent.com/72133257/220948852-e7d0cc2b-76e1-4761-82d0-3cea51f41745.png)

- [ ] Yo haría los inputs de fecha en historia de vida un poco más grandes, para que cubran un poco más de espacio, aunque habría que ver cómo quedaría
![Image](https://user-images.githubusercontent.com/72133257/220949876-77852856-a187-403d-8a71-595fecfc552c.png)

- [ ] En Persona Relacionada, los inputs de la izquierda son más pequeños que los de la derecha, y la separación con las labels es demasiado grande
![Image](https://user-images.githubusercontent.com/72133257/220950728-e9c6fb8c-90b3-4cc0-a745-d1fdf684d796.png)

**Comment by crisselene** [comment]
- en sesión arreglado
- el recuerdo está arreglado, he intentado que los modales se vean lo mejor posible pero no puedo evitar que se corte un poco si la comprobación ( ✔ ) está dentro del input
- separación en las escalas
- no lo he hecho más grande porque quedaba peor para hacerlo responsive, lo que sí he hecho ha sido separar un poco más los campos y las fechas para que de una sensación de mayor amplitud, pero tampoco demasiado.

**Comment by SerArias** [comment]
- [ ] En la vista de "datos de la sesión" me parece que sigue siendo más pequeño el input de la fecha que el de la etapa, pero no sé si es que directamente no se puede igualar el tamaño.
- [ ] Con la pantalla mas o menos a la mitad de tamaño, fecha y etapa se ven un tanto mal (tanto el input de fecha como sus respectivos *). ¿Tal vez haya que ponerlos para ese tamaño directamente uno encima del otro?

![Image](https://user-images.githubusercontent.com/99254373/226165699-cc492bf1-a0d0-4ba7-b80f-fced368dddbc.png)

**Comment by crisselene** [comment]
solucionado
