### ISSUE TITLE
Código: Crear espectro de datos reales

### ISSUE THREAD

**Issue by erosguerrero** [NILGroup/TFG-22-23-Recuerdame2.0#180]
- [x] Recuerdos serios
- [x] Personas Relacionadas
- [x] Números de teléfono no real
- [x] Cuidadores
- [x] Sesiones
- [x] Terapeutas
- [x] Pacientes

**Comment by SerArias** [comment]
He modificado la descripción de la actividad, que seguía haciendo referencia a Miguel
