### ISSUE TITLE
Código: cambiar el título del propio pdf

### ISSUE THREAD

**Issue by crisselene** [NILGroup/TFG-22-23-Recuerdame2.0#184]
Cambiar el título, poner informe de sesión: titulo de la sesión
Quitar el #número

![Image](https://user-images.githubusercontent.com/35759827/218511572-7599019b-eb3d-4c62-9581-0951057433a8.png)

**Comment by Lurngi** [comment]
He cambiado el nombre a todos los PDF. Agradecería que valoraseis los nuevos nombres

**Comment by PabloMartinez01** [comment]
El titulo del pdf de sesion sigue igual

**Comment by Lurngi** [comment]
Corregido

**Comment by SerArias** [comment]
Actualmente, aparece como "Informe de sesión"; pero debería ser "Informe de sesión: título", ¿no?
