### ISSUE TITLE
Código: Cambiar el nombre del archivo del pdf

### ISSUE THREAD

**Issue by crisselene** [NILGroup/TFG-22-23-Recuerdame2.0#185]
- [x] Sesion (Ya implementado como Sesion + nombre del paciente + titulo sesion)
- [x] Evaluacion (Ya implementado como Seguimiento + nombre del paciente + fecha)
- [x] Historia de Vida (Ya implementado como paciente + fecha)

**Comment by Lurngi** [comment]
Los nombres no me terminan de convencer, agradecería valoraciones

**Comment by PabloMartinez01** [comment]
![Image](https://user-images.githubusercontent.com/95294905/222897429-e1fc90f1-b27d-4eae-b26b-b1cf7e110060.png)

Creo que no es muy conveniente que el nombre tenga espacios en blanco. A mi parecer habría que quitarlos

**Comment by Lurngi** [comment]
Corregido. Aunque no debería haber problema, he reemplazado los espacios por _

**Comment by SerArias** [comment]
- [ ] En el nombre del pdf generado, a mí me aparece la fecha en formato dd_mm_yyyy. No sé si ha sido la decisión final, si es cosa de mi SO, ...
- [ ] En informe de sesión no aparece la fecha en el nombre del pdf generado. ¿Es porque nos dijeron que la fecha en este tipo de informes es irrelevante o porque se nos ha pasado?

**Comment by Lurngi** [comment]
- Lo de la fecha no es decisión final, pero lo cambié porque si no quedaba raro

- Lo de la fecha en informe de sesión es algo ambiguo. Decidí poner el título de la sesión. Tambien contando con que en windows hay un limite de caracteres predeterminado para los archivos. Supongo que en MAC y Linux tambien pero no lo miré, sinceramente
