### ISSUE TITLE
Código: Refactorizar el nombre de la entidad "Paciente" a "Usuarios"

### ISSUE THREAD

**Issue by Lurngi** [NILGroup/TFG-22-23-Recuerdame2.0#190]

**Comment by Lurngi** [comment]
Falta cambiar las rutas

**Comment by SerArias** [comment]
Creo que se debería cambiar también "Paciente" por "Usuario" en la NavBar del cuidador.

![Image](https://user-images.githubusercontent.com/99254373/226192622-2c6d7778-338e-4d19-a406-d4c714cc4036.png)

**Comment by crisselene** [comment]
hecho
