### ISSUE TITLE
Código: Tooltips en los iconos

### ISSUE THREAD

**Issue by Lurngi** [NILGroup/TFG-22-23-Recuerdame2.0#192]
- [x] Añadir tooltips a todos los iconos de la aplicación
- [x] Aumentar el tamaño de letra
- [x] tooltip en el icono personitas de navBar
- [x] Corregir tooltip contacto en persona relacionada. (Se refiere a si es el contacto principal)

**Comment by Lurngi** [comment]
Hay que corregir esto, se refiere al contacto principal, no a si mantienen contacto

![Image](https://user-images.githubusercontent.com/72133257/221624130-15399d48-2c95-4faf-8ef6-668c3f1ae835.png)

**Comment by SerArias** [comment]
- [ ] Al posarse sobre la esquina superior izquierda de algunos iconos, el tooltip aparece en la esquina inferior izquierda de la pantalla.

![Image](https://user-images.githubusercontent.com/99254373/226166992-ef51ca5d-4c0a-4076-96ec-ef637ede5c32.png)

- [ ] En algunos iconos, por ejemplo en el de la papelera, el tooltip aparece a la izquierda del icono y no encima de este, como ocurre con la mayoría de ellos. No sé si es un error propiamente dicho o es simplemente que se coloca ahí por ser el que más a la derecha está. En cualquier caso, lo dejo por aquí.

![Image](https://user-images.githubusercontent.com/99254373/226167043-a04965dd-cc66-4117-aec4-b519f8ff68e9.png)

**Comment by Lurngi** [comment]
Lo de que aparezca el tooltip en la parte superior izquierda no he conseguido arreglarlo. Espero que @crisselene pueda.
Lo de que se coloque a la izquierda es automatico cuando no entra encima.
Puntos eliminados de todos los tooltips
