### ISSUE TITLE
Memoria: Reescribir apartado SweetAlert

### ISSUE THREAD

**Issue by Lurngi** [NILGroup/TFG-22-23-Recuerdame2.0#197]
Hay que añadir el modal de confirmación. El de deshacer ya está, aunque no implementado en el código por el momento

**Comment by crisselene** [comment]
Cuando se nombra a Jackob Niesen igual debería ponerse una referencia, no estoy segura, peor puede ser que sea necesaria.

**Comment by SerArias** [comment]
Corregidos algunos aspectos de cohesión.
No sé si deberíamos cambiar el primer párrafo, que Virginia suele hacer mucho hincapié en que no comentemos aspectos negativos de "Recuérdame 1.0":


![Image](https://user-images.githubusercontent.com/99254373/221820858-f5885ac0-7bbd-46ee-9eaa-269632785644.png)
