### ISSUE TITLE
Código: Refactorizar estilo vista login y registro

### ISSUE THREAD

**Issue by Lurngi** [NILGroup/TFG-22-23-Recuerdame2.0#198]

**Comment by crisselene** [comment]
- se ha cambiado la vista de verificación del correo

**Comment by SerArias** [comment]
Que la validación en el login y en el registro sea así, ¿tiene alguna justificación o falta por ponerle la validación que hemos puesto en el resto de la aplicación?

![Image](https://user-images.githubusercontent.com/99254373/226194729-d524972d-f071-4c7d-9024-7148a1a814ef.png)

**Comment by crisselene** [comment]
es así, únicamente sale la otra verificación si intentas enviar y la info es incorrecta. Si no has enviado nada y ese campo debe rellenarse, sale ese mensajito amarillo siempre
