### ISSUE TITLE
Memoria: Redacción de la introducción Hito 0

### ISSUE THREAD

**Issue by erosguerrero** [NILGroup/TFG-22-23-Recuerdame2.0#2]
Escribir la introducción de la memoria en el documento de Overleaf.

**Comment by Lurngi** [comment]
Se ha escrito todo lo correspondiente al hito 0

**Comment by SerArias** [comment]
Añadir motivación de aumento de casos de Alzheimer en las próximas décadas

**Comment by crisselene** [comment]
añadido motivación de aumento de casos de Alzheimer en las próximas décadas
