### ISSUE TITLE
Código: Calendario

### ISSUE THREAD

**Issue by Lurngi** [NILGroup/TFG-22-23-Recuerdame2.0#20]

**Comment by crisselene** [comment]
cuando le doy a modificar y guardo los cambios, se guardan pero en la vista me dejan de aparecer las sesiones. Si actualizo vuelven a a aparecer

**Comment by crisselene** [comment]
botones pequeños

![Image](https://user-images.githubusercontent.com/35759827/198021820-f347675e-d0eb-46a5-aba3-9264d522543b.png)

**Comment by crisselene** [comment]
apartado de horarios de semana-día sin sentido, cuándo le das a añadir un evento a una hora un determinado día, no te da ni el día que has seleccionado y tampoco se fija el evento en una hora si no que se fija durante todo el día.

**Comment by SerArias** [comment]
Ya he solucionado todos los problemas. Los botones han pasado de ser "btn-sm" a "btn-md". Los apartados **semana** y **día** ahora ya no muestran las horas, tan solo las actividades asociadas al día. El scroll ahora es únicamente el del propio calendario, y no el exterior.
