### ISSUE TITLE
Código: Cambiar colores de los botones modal calendario

### ISSUE THREAD

**Issue by Lurngi** [NILGroup/TFG-22-23-Recuerdame2.0#200]

**Comment by crisselene** [comment]
yo pondría el botón de eliminar o bien, vacío pero con la línea azul (como en recuerdo) o gris entero.

![Image](https://user-images.githubusercontent.com/35759827/220143812-9d6935a9-711b-4b05-9481-ba97487cfac1.png)

opción 1 ejemplo:


![Image](https://user-images.githubusercontent.com/35759827/220144072-5dfb5c62-8f80-4f78-b908-ad9405fa674f.png)

opción 2 ejemplo:


![Image](https://user-images.githubusercontent.com/35759827/220144146-8c698499-f889-43b7-bb01-8661c43171c0.png)

**Comment by SerArias** [comment]
Por el momento, lo dejo como el botón de "Generar PDF" (btn-outline-primary).
