### ISSUE TITLE
Código: Informe de seguimiento

### ISSUE THREAD

**Issue by Lurngi** [NILGroup/TFG-22-23-Recuerdame2.0#22]

**Comment by crisselene** [comment]
la visualización de los informes no me funcionan, me pone: Class "Codedge\Fpdf\Fpdf\Fpdf" not found

**Comment by Lurngi** [comment]
Te falta instalar la biblioteca en local, haciendolo debería funcionar

**Comment by Lurngi** [comment]
Arreglado

**Comment by crisselene** [comment]
botones pequeños para guardar el informe de seguimiento

**Comment by crisselene** [comment]
si no añado todos los campos salta pantalla de error en vez indicar lo que me hace falta por rellenar

**Comment by erosguerrero** [comment]
Cuando creas un nuevo informe creo que debería llevar a la lista de informes y no a ver ese informe en concreto por consistencia con el resto de la aplicación

**Comment by erosguerrero** [comment]
![Image](https://user-images.githubusercontent.com/94256335/200089639-b7d97988-85fd-4225-89fd-927b8e3d4598.png)

Creo que una disposición más adecuada de los botones serían

Atrás, Editar y en la parte más derecha de la página Generar PDF

**Comment by Lurngi** [comment]
En Recuerdame 1 te redirije siempre a la vista show de lo que acabas de mostrar, es un cambio que hay que hacer en el resto de la página.
En cuanto a los botones, en Recuerdame 1 están en el orden Generar PDF -> Atrás. He añadido el de editar para facilitar el acceso y no tener que hacer 2 redirecciones (Aunque igual no está bien al igual que lo de mostrar el cuidador en la vista de paciente del hito anterior)

**Comment by erosguerrero** [comment]
Creo que Virginia nos comentó que ya podíamos hacer cambios si eran en el nombre de la usabilidad, siempre y cuando no cambiara la funcionalidad (que eso es cosa únicamente del usuario). Sin embargo, si quieres dejarlo así y ya, tienes mi like para pasarlo

**Comment by Lurngi** [comment]
Botones recolocados
