### ISSUE TITLE
Memoria: Correcciones capítulo 7 (Cada uno su trabajo)

### ISSUE THREAD

**Issue by Lurngi** [NILGroup/TFG-22-23-Recuerdame2.0#226]
- [x] Cristina
- [x] Eros
- [x] Pablo

**Comment by crisselene** [comment]
Añadido apartado 5.1.5 rediseño de los documentos y  5.2.7 control de duplicados

**Comment by Lurngi** [comment]
He eliminado el apartado 5.1.5 y movido su contenido a los apartados de rediseño de vistas y observaciones. Al apartado 5.2.7 le he hecho cambios menores.
