### ISSUE TITLE
Código: Multimedia en Cuidador

### ISSUE THREAD

**Issue by PabloMartinez01** [NILGroup/TFG-22-23-Recuerdame2.0#230]
- [x] Crear cuidador
- [x] Ver cuidador
- [x] Actualizar cuidador
- [x] Limitar ficheros

**Comment by Lurngi** [comment]
Hay que valorar el formato de dropzone en cuidador y paciente, como dijo Virginia en la memoria.
En cuanto a funcionalidad creo que está bien, doy like
