### ISSUE TITLE
Código: responsive tablas

### ISSUE THREAD

**Issue by crisselene** [NILGroup/TFG-22-23-Recuerdame2.0#231]

**Comment by crisselene** [comment]
listado de informe de seguimiento no es responsive: 

![Image](https://user-images.githubusercontent.com/35759827/220620780-54387964-9020-40a1-b754-0f96b681f8c0.png)

**Comment by Lurngi** [comment]
He hecho lo que he podido, espero haberlo solucionado

**Comment by Lurngi** [comment]
En el modal, la cabecera no redimensionar bien. Probar añadiendo este codigo 

$('#AUDdetailsModal').on('shown.bs.modal', function () {
       var table = $('#lstProblems').DataTable();
       table.columns.adjust();
   });
