### ISSUE TITLE
Memoria: Añadir librerías en el capítulo de "Herramientas"

### ISSUE THREAD

**Issue by Lurngi** [NILGroup/TFG-22-23-Recuerdame2.0#234]
- [x] BootStrap 5
- [x] JQuery
- [x] FontAwesome
- [x] FPDF
- [x] DataTable
- [x] SweetAlert
- [x] Animate
- [x] FullCalendar

**Comment by crisselene** [comment]
- [ ] Cambié _"jquery: la base de la mayoría..."_ por _"jquery: conforma la base de la mayoría..."_ ✔ 
- [ ] errores ortográficos ✔ 
- [ ] en la última, Animate, al final de la frase dice: _"para dar una sensación de dinamismo al **usuario**."_  ¿yo igual pondría _sensación de dinamismo a la **aplicación_**? Bueno, creo que lo que has puesto está bien, pero por si lo quieres considerar. ❓ 
- [ ] creo que las descripciones están perfectas 🥳

**Comment by SerArias** [comment]
Creo que las herramientas, en el segundo párrafo, no deben ir en cursiva. 


![Image](https://user-images.githubusercontent.com/99254373/221826105-33cc2b65-a631-4172-9700-e2182055a472.png)


Por el momento no lo cambio, por si hay alguna razón por la que estén así. Por lo demás, me parece que está muy bien hecho.
