### ISSUE TITLE
Código: Igualar el tamaño de la columna Acciones en todas las tablas

### ISSUE THREAD

**Issue by Lurngi** [NILGroup/TFG-22-23-Recuerdame2.0#236]

**Comment by Lurngi** [comment]
Ya puestos, reajustar las columnas en el index de los pacientes

![Image](https://user-images.githubusercontent.com/72133257/222831700-b16a4dd2-e3ae-42db-a450-2eb28f30fd00.png)

**Comment by SerArias** [comment]
La columna acciones es más pequeña de lo normal en:

- [ ] Listado de informes de seguimiento.

La columna de acciones es más grande de lo normal en:

- [ ] Listado de personas relacionadas.
- [ ] Lista de cuidadores.

**Comment by Lurngi** [comment]
Voy a cerrar esta tarea porque ha acabado con nuestra salud mental. Cuando estén todos los cambios hechos intentaré una última cosa con DataTables, pero no espereis nada
