### ISSUE TITLE
Código: Eliminar disabled de las vistas

### ISSUE THREAD

**Issue by Lurngi** [NILGroup/TFG-22-23-Recuerdame2.0#237]
Con el script para los vista de show, los if($show) disabled endif ya no son necesarios y convendría eliminarlos

**Comment by PabloMartinez01** [comment]
Te doy like pero como comentario: No borrar sistemáticamente todos los if ($show), hay elementos de multimedia que lo utilizan. No obstante corroboro que esto no es necesario para los DISABLED, en otras ocasiones puede ser que si.
