### ISSUE TITLE
Memoria: Retrospectiva Pablo

### ISSUE THREAD

**Issue by Lurngi** [NILGroup/TFG-22-23-Recuerdame2.0#238]

**Comment by SerArias** [comment]
Corregidos algunos errores de gramática y reescrita alguna cosilla que a mi parecer no se entendía del todo bien.

**Comment by Lurngi** [comment]
He corregido algunas cosas que se seguían sin entender o no eran del todo correctas. Tambien he añadido un parrafo final para explicar cómo solucionamos las discusiones que se nombran
