### ISSUE TITLE
Memoria: sección 5.2.6 control de duplicados

### ISSUE THREAD

**Issue by crisselene** [NILGroup/TFG-22-23-Recuerdame2.0#239]

**Comment by Lurngi** [comment]
He realizado varios cambios en la redacción.

- [ ] Falta añadir los simbolos de warning y error en las imagenes
- [ ] En la segunda imagen, en mi opinión debería poner que no se puede porque pertenece a un terapeuta, al igual que en la primera pone que pertenece a un cuidador ya registrado
- [ ] No se deberían cambiar los datos del cuidador en caso de que el email ya esté registrado, solo asignarlo. Al menos en mi opinión, nuevamente
