### ISSUE TITLE
Código: Generar historia de vida (sin archivos)

### ISSUE THREAD

**Issue by Lurngi** [NILGroup/TFG-22-23-Recuerdame2.0#24]

**Comment by crisselene** [comment]
multimedia sin probar por falta de imágenes, pendiente de terminar cuando se sepa cómo se van a añadir las imágenes a la base de datos.

**Comment by Lurngi** [comment]
Creo que este texto debería estar centrado y tener color negro, en lugar de grisaceo

![Image](https://user-images.githubusercontent.com/72133257/198745217-41c0c798-d84a-4517-a4d6-0157947a2250.png)

**Comment by Lurngi** [comment]
Hay que colocar mejor los recuerdos en el PDF. Quizás poner uno por página.


![Image](https://user-images.githubusercontent.com/72133257/198746090-325d73ba-f3df-4a4d-8819-d24b57bd255e.png)

**Comment by crisselene** [comment]
El corte de los recuerdos y las imágenes ya está solucionado. Queda pendiente hacer pruebas cuando se puedan subir imágenes a la base de datos. En cuanto al mensaje grisáceo, queda pendiente de aprobación por parte del resto del equipo para el cambio puesto que ese era el que aparecía en Recuérdame 1.0

**Comment by Lurngi** [comment]
![Image](https://user-images.githubusercontent.com/72133257/199329745-15bb0d80-9331-404b-87aa-37533b4351ba.png)

Sigue pasando

**Comment by crisselene** [comment]
no veo el problema en la foto adjuntada @Lurngi

**Comment by Lurngi** [comment]
Aunque la imagen quepa en la página debería estar por encima del footer de la misma, no pegando con el borde de la hoja

**Comment by crisselene** [comment]
debería estar solucionado, aun así, queda pendiente revisarlo cuando tengamos más imágenes con otros largos u anchos.
