### ISSUE TITLE
Memoria: Trabajo futuro

### ISSUE THREAD

**Issue by crisselene** [NILGroup/TFG-22-23-Recuerdame2.0#249]
Añadir ubicación con google maps

**Comment by erosguerrero** [comment]
![Image](https://github.com/NILGroup/TFG-22-23-Recuerdame2.0/assets/94256335/9e93d9df-1ff9-482b-a06e-71bba53c6d13)

Que se sincronice usando analisis del video (IA supongo) y además que la narración se espere quietita si el vídeo tiene audio

**Comment by PabloMartinez01** [comment]
Validación formulario diagnóstico

**Comment by crisselene** [comment]
fallo en la enfermedad no es obligatorio y si sale error de que no puede ser null:


![Image](https://github.com/NILGroup/TFG-22-23-Recuerdame2.0/assets/35759827/e038b203-f705-4764-9588-e975d0e1d8ca)

**Comment by crisselene** [comment]
Revisar que pasa cuando solo tienes un diagnóstico creado

**Comment by crisselene** [comment]
Si tienes una persona como contacto, si la visualizas no se marca la casilla de contacto marcada

**Comment by crisselene** [comment]
el checkbox de un recuerdo apto, cuando le das a editar no se ve marcado

**Comment by crisselene** [comment]
si editas un recuerdo se borran los recuerdos asociados

**Comment by crisselene** [comment]
revisar el algoritmo para calcular el número de sesiones anteriores en informe de seguimiento

**Comment by crisselene** [comment]
revisar el invalid date cuando no se introducen fechas

**Comment by crisselene** [comment]
borrar un cuidador existente no redirige

**Comment by crisselene** [comment]
Al asignar terapeutas, se eliminan también las personas cuidadoras

**Comment by crisselene** [comment]
buscar alternativas de calendario para juntarlo con google calendar 
errores de calendario. muchos errores de compatibilidad, en los móviles no se ve bien

**Comment by crisselene** [comment]
los fpdfs no pueden guardar información de archivos con extensiones raras
