### ISSUE TITLE
Memoria: otros apuntes de diseño

### ISSUE THREAD

**Issue by crisselene** [NILGroup/TFG-22-23-Recuerdame2.0#274]
- hairlines (patrón IU)
- responsive
- imagenes por defecto

**Comment by Lurngi** [comment]
Yo lo juntaría todo dentro del rediseño de interfaz, no le veo sentido a tener 3 apartados nuevos extra referentes al nuevo diseño, pero que decida Virginia. Por lo demás, he realizado pequeñas correcciones
