### ISSUE TITLE
Código: Arreglar imagen cuidador

### ISSUE THREAD

**Issue by Lurngi** [NILGroup/TFG-22-23-Recuerdame2.0#280]
Al pulsar el botón "Eliminar imagen" en editar, se elimina directamente. Los cambios no deberían guardarse hasta que se envíe el form fiman.

Además, algunas imagenes se deforman

![Image](https://user-images.githubusercontent.com/72133257/227517332-e354959c-2919-4f0a-b020-4e76bd8eee8c.png)

**Comment by crisselene** [comment]
está hecho pero en el editar, el eliminar foto no funciona @PabloMartinez01
