### ISSUE TITLE
Código: Correcciones Recuerdo

### ISSUE THREAD

**Issue by Lurngi** [NILGroup/TFG-22-23-Recuerdame2.0#287]
- [x] La etiqueta ya no existe, hay que reemplazar esta columna con la que corresponde.
![Image](https://user-images.githubusercontent.com/72133257/229137012-dc61b77d-e7d6-4454-823c-70aa51536829.png)

- [ ] La tabla de personas relacionadas y la de añadir existente no son como la del showbypaciente de Personas Relacionadas. Hay que cambiarlo por la consistencia
![Image](https://user-images.githubusercontent.com/72133257/229137334-f1b7defb-92dc-4d87-bc01-8e524376c53c.png)

- [x] Dado que la etapa es obligatoria y la categoría no, tiene sentido cambiarlas de lugar, para de esta forma no mostrar el resto si no se han rellenado en la vista de show
![Image](https://user-images.githubusercontent.com/72133257/229137979-94519f9b-f11d-42eb-ab62-df0a59a7dfe4.png)

**Comment by crisselene** [comment]
la segunda tarea no la entiendo

**Comment by SerArias** [comment]
@crisselene creo que se refiere a que cuando nos vamos a la vista de Personas Relacionadas (es decir, en el listado), la tabla muestra el nombre, la localidad y la relación. Sin embargo, cuando vemos las Personas Relacionadas de un Recuerdo; o cuando añadimos en un Recuerdo una Persona Relacionada existente, la tabla sólo muestra el nombre y la relación.

![Image](https://user-images.githubusercontent.com/99254373/234607658-8bc8f82e-90eb-40c2-8940-a22f70c33306.png)

![Image](https://user-images.githubusercontent.com/99254373/234607796-516783e5-5db7-412b-810f-7ec5e9a055c1.png)

![Image](https://user-images.githubusercontent.com/99254373/234608036-9c2c111e-8592-49dd-b3cc-a4109bd1a245.png)
