### ISSUE TITLE
Código: Cambios Informe de Sesión

### ISSUE THREAD

**Issue by Lurngi** [NILGroup/TFG-22-23-Recuerdame2.0#289]
- [x] Mostrar datos relevantes de la sesión al cerrar el informe (descripción y objetivos)
- [x] Añadir campo de propuestas
- [x] Corregir que no se guarde el nivel de complejidad.
- [x] Añadir todos los campos al PDF

**Comment by SerArias** [comment]
En el PDF no se muestran la etapa, la secuencia de acciones, las barreras ni los facilitadores. Además, la duración no es la misma en la vista y en el pdf.

![Image](https://user-images.githubusercontent.com/99254373/234621936-9487cb9f-c222-4c79-99d7-acae1b083c8b.png)

![Image](https://user-images.githubusercontent.com/99254373/234621937-ad7bc138-fd10-4c6b-a65f-86601ec85c45.png)
