### ISSUE TITLE
Memoria: estado del arte IA

### ISSUE THREAD

**Issue by crisselene** [NILGroup/TFG-22-23-Recuerdame2.0#293]
puntos redactados:
- 2.4.1.
- 2.4.2.
- 2.4.3.
- 2.4.4.

**Comment by crisselene** [comment]
@SerArias especialmente me interesa que leas tú estos puntos para revisarlos

**Comment by SerArias** [comment]
Todos los puntos revisados y corregidos. Están francamente bien. No sé si de aquí a que entreguemos la memoria añadiré alguna cosa nueva. Solo tengo dudas de si el punto **2.4.4** debe de estar ahí, o si simplemente debemos dejarlo para otros capítulos.
