### ISSUE TITLE
Memoria: Herramientas vídeos

### ISSUE THREAD

**Issue by erosguerrero** [NILGroup/TFG-22-23-Recuerdame2.0#294]
La revisión en esta es importante, hay muucho texto. Y por saber si se entiende bien el proceso.

**Comment by crisselene** [comment]
-he reemplazado algún "multimedia" por "archivo" para que no suene tan redundante porque tienes que usar mucho esa palabra, comprensiblemente, pero queda un poco raro repetirla tanto.
- corregidos algunos errores mofológicos
- en esta frase de ffmpeg: "Además, tampoco encontramos limitantes en el tamaño de los tamaños." creo que querías decir vídeos, pero como no lo sé, de momento la voy a cambiar por: "Además, tampoco encontramos limitantes en la dimensión de los tamaños." aunque no le veo mucho el sentido.
- los títulos de google transcoder y creatomate están en mayúsculas por algún motivo?
- en creatomate dice esto: _"Esta librería
permite la utilización de plantillas para la generación de vídeos y tiene una
**curva de aprendizaje más elevada que el resto**, pues tiene una documentación
mucho más cuidada, siendo la única que tiene documentación exclusiva para
Laravel (nuestro framework ) lo que la hace mucho más fácil de gestionar"_
  Eso no sería que la curva de aprendizaje es menos elevada por que es más fácil?
-

**Comment by erosguerrero** [comment]
**he reemplazado algún "multimedia" por "archivo" para que no suene tan redundante porque tienes que usar mucho esa palabra, comprensiblemente, pero queda un poco raro repetirla tanto.**
Perfecto! 
**corregidos algunos errores mofológicos**
Nice
**en esta frase de ffmpeg: "Además, tampoco encontramos limitantes en el tamaño de los tamaños." creo que querías decir vídeos, pero como no lo sé, de momento la voy a cambiar por: "Además, tampoco encontramos limitantes en la dimensión de los tamaños." aunque no le veo mucho el sentido.**
Quería decir, donde esta tamaños, archivos.

**los títulos de google transcoder y creatomate están en mayúsculas por algún motivo?**
Porque son nombres propios.

**en creatomate dice esto:
"Esta librería
permite la utilización de plantillas para la generación de vídeos y tiene una
curva de aprendizaje más elevada que el resto, pues tiene una documentación
mucho más cuidada, siendo la única que tiene documentación exclusiva para
Laravel (nuestro framework ) lo que la hace mucho más fácil de gestionar"**

**Eso no sería que la curva de aprendizaje es menos elevada por que es más fácil?**


![Image](https://user-images.githubusercontent.com/94256335/231104243-9c99d2e7-6b8c-49f0-b9dd-e3a5282af36c.png)

Yo creo que a más alta es mejor

**Comment by erosguerrero** [comment]
San google habló sobre la curva de aprendizaje, a más baja mejor

**Comment by crisselene** [comment]
Están literalmente, todo en mayúsculas:

![Image](https://user-images.githubusercontent.com/35759827/231106673-fe7be1c0-cb11-4f03-a995-99ee4d6f90ea.png)
