### ISSUE TITLE
Memoria: 3.2 Investigación sobre la integración continua

### ISSUE THREAD

**Issue by erosguerrero** [NILGroup/TFG-22-23-Recuerdame2.0#3]
Estudiar y probar GitHub Actions y Jenkins para decidir cual usaremos.

**Comment by Lurngi** [comment]
Hemos decidido posponer el estudio al inicio del siguiente hito porque hemos considerado que la refactorización era más prioritaria

**Comment by Lurngi** [comment]
Hemos decidido posponer el estudio al inicio del siguiente hito porque hemos considerado que la refactorización era más prioritaria
