### ISSUE TITLE
Código: Sistema de subida de archivos

### ISSUE THREAD

**Issue by erosguerrero** [NILGroup/TFG-22-23-Recuerdame2.0#34]
Poder subir:
- [x] Imágenes
- [x] PDF
- [x] Vídeos

Pendiente en CREAR:
- [x] Recuerdo
- [x] Sesion
- [x] Foto del Paciente
- [x] Historia de vida
- [x] Recuerdos en Informe de Sesión
- [x] Persona Relacionada

Pendiente en UPDATE:
- [x] Recuerdo
- [x] Sesion
- [x] Foto del Paciente
- [x] Historia de vida
- [x] Recuerdos en Informe de Sesión
- [x] Persona Relacionada

**Limitar imagenes a png, jpg
**Limitar pdf a .pdf
**Limitar vídeo a mp4, avi, wav

**Comment by erosguerrero** [comment]
A la espera de tutoría con Samer. Encriptado. Ética. Ley.
Archivos: Imágenes, PDF's y vídeos.

Vistas que deben asociarse: Recuerdo y Sesión.

**Comment by erosguerrero** [comment]
GUIA MUILTIMEDIA:
https://docs.google.com/document/d/1_U_33DUe2veqocVaqxeJHqOrRnPa42um4DtJHtKlse8/edit

**Comment by erosguerrero** [comment]
Recuerdo no redirecciona

**Comment by Lurngi** [comment]
En las vistas de editar, no se entiende que el check elimine los multimedia. Hay que repensar cómo hacerlo porque no es intuitivo

**Comment by crisselene** [comment]
de acuerdo con Adrián, pero de momento doy like porque la funcionalidad, de momento, parece estar bien.
