### ISSUE TITLE
Código: Arreglar modal recuerdo Informe Sesión

### ISSUE THREAD

**Issue by Lurngi** [NILGroup/TFG-22-23-Recuerdame2.0#341]
- [x] Pone "Crear" en lugar de "Editar"
- [x] No se importan los datos

**Comment by crisselene** [comment]
![Image](https://user-images.githubusercontent.com/35759827/235156215-1f2606c1-f682-4bae-a977-823811d36431.png)

sale este error también en este modal de recuerdo
