### ISSUE TITLE
Memoria: Sistema de subida de archivos (Reunión con Samer)

### ISSUE THREAD

**Issue by erosguerrero** [NILGroup/TFG-22-23-Recuerdame2.0#35]

**Comment by Lurngi** [comment]
He hecho correcciones mínimas y añadido, por el momento, el video que grabé yo de la reunión, a falta de escoger cual de todos usaremos.
También salta un Warning, no he sabido solucionarlo y dudo que sea importante

**Comment by crisselene** [comment]
el warning es porque no hay section, pero no pasa nada, no es necesario solucionarlo
