### ISSUE TITLE
Código: corregir faltas ortográficas

### ISSUE THREAD

**Issue by crisselene** [NILGroup/TFG-22-23-Recuerdame2.0#394]
Hay que corregir todos los pdfs y asegurarse de que todos los textos son utf8
Género lleva tilde:

![Image](https://user-images.githubusercontent.com/35759827/236903927-524de061-c83f-429d-8f28-eb75e5767c32.png)

**Comment by SerArias** [comment]
Cambiar "diagnostico" por "diagnóstico"

![Image](https://github.com/NILGroup/TFG-22-23-Recuerdame2.0/assets/99254373/def3df3d-20f4-4099-be56-e2d71a957a86)

**Comment by crisselene** [comment]
![Image](https://github.com/NILGroup/TFG-22-23-Recuerdame2.0/assets/35759827/369ac339-cbbf-4042-9ca2-8ccc81b82bfc)

**Comment by crisselene** [comment]
![Image](https://github.com/NILGroup/TFG-22-23-Recuerdame2.0/assets/35759827/3c1d28dc-330c-4daa-9f5e-fb174775ad9e)

**Comment by crisselene** [comment]
![Image](https://github.com/NILGroup/TFG-22-23-Recuerdame2.0/assets/35759827/615204c6-f0eb-4af4-bb9c-7c4753dc9618)
