### ISSUE TITLE
Código: Migración del proyecto y refactorización del código (old)

### ISSUE THREAD

**Issue by erosguerrero** [NILGroup/TFG-22-23-Recuerdame2.0#4]
Hay que migrar el proyecto Recuerdame a este repositorio y refactorizar todo el código para adaptarlo al framework de Laravel

**Comment by erosguerrero** [comment]
Se han creado los primeros controllers UsuarioControllers, MultimediaController, RecuerdosController y SesionesController casi en su plenitud. Se ha creado la vista de registro (Adrían) y parece funcionar relacionada con UsuarioController. Se proponen mejoras de seguridad (hash de contraseñas) no implementadas en Recuerdame1.

**Comment by crisselene** [comment]
Realizadas vistas de crear paciente, listar pacientes y modificar paciente.
Se ha implementado tal y cómo se realizó en recuérdame 1.0 usando plantillas de Blade.
Quedan pendientes mejoras que  en la versión antigua no se realizaron como impedir que la fecha de nacimiento sea posterior a la actual o que se permitan más géneros que hombre o mujer.
