### ISSUE TITLE
Código: Recuerdo max y min puntuación

### ISSUE THREAD

**Issue by PabloMartinez01** [NILGroup/TFG-22-23-Recuerdame2.0#40]

**Comment by erosguerrero** [comment]
![Image](https://user-images.githubusercontent.com/94256335/198049167-8dcc5523-da1d-4ed7-a035-c9f735860c5a.png)

Basicamente es esto en Ver y editar recuerdo

**Comment by Lurngi** [comment]
En Recuerdame 1 las puntuaciones son de 0 a 5, no de 0 a 10. Creo que hay que respetarlo

**Comment by erosguerrero** [comment]
![Image](https://user-images.githubusercontent.com/94256335/198899768-0cd29833-8199-40d8-9226-4a313c7a29aa.png)

I dont think so :)
