### ISSUE TITLE
Memoria: Capitulo 7 y traducción

### ISSUE THREAD

**Issue by Lurngi** [NILGroup/TFG-22-23-Recuerdame2.0#442]
Aunque Virginia no lo haya dicho, además de las correcciones habría que añadir la parte del trabajo futuro de Recuérdame 1 que no hemos tocado

**Comment by crisselene** [comment]
Hay que añadir la traducción del GDPR <3

**Comment by SerArias** [comment]
@PabloMartinez01 ya están incorporados los cambios relativos a las asignaturas y los dos últimos párrafos de conclusiones

**Comment by PabloMartinez01** [comment]
Corregido 7.2

**Comment by PabloMartinez01** [comment]
Cambiado por completo el 7.1
