### ISSUE TITLE
Código: Arreglar footer y añadirle scroll ascendente rápido

### ISSUE THREAD

**Issue by crisselene** [NILGroup/TFG-22-23-Recuerdame2.0#45]

**Comment by SerArias** [comment]
Las cruces para poder eliminar las imágenes pasan por encima del _scrollbar_ . Adjunto imagen.

![Image](https://user-images.githubusercontent.com/99254373/198868085-32246b3f-78f5-49ff-816c-5a81bdaad2b9.png)

**Comment by SerArias** [comment]
En algunas secciones tapa los botones y no permite interactuar con ellos. La imagen que adjunto es de crear sesión, aunque el mismo problema se repite en varias ocasiones.

![Image](https://user-images.githubusercontent.com/99254373/198869501-6f6dd818-eaea-43e8-ad1b-c06e85c4257e.png)

**Comment by Lurngi** [comment]
Que los botones aparezcan por encima del footer es cosa de los propios botones. Queda pendiente para cuando hagamos todo lo relacionado a la visualización de multimedia

**Comment by Lurngi** [comment]
Ocultación de botones arreglada

**Comment by erosguerrero** [comment]
Creo que debería ocultarse si ya está en la página superior del scroll

**Comment by erosguerrero** [comment]
Hecho el scroll hider

**Comment by Lurngi** [comment]
![Image](https://user-images.githubusercontent.com/72133257/199300555-1c313d19-c715-4a48-8bca-8ee6312e1b71.png)

Al aparecer el botón, de vez en cuando se muestra así

**Comment by Lurngi** [comment]
La acción de volver al inicio de página ocupa todo el div en lugar de solo la imagen

**Comment by erosguerrero** [comment]
El error de la imagen pixelada debe ser repetible para que pueda echarle un ojo, y disponer de los pasos.
En cualquier caso se plantea en un futuro: "Tarea diseño nueva imagen flecha personalizada"

Solucionado el tema del div.

**Comment by Lurngi** [comment]
Para reproducir el error simplemente tienes que ir a una vista con scroll y la primera vez que aparece el botón se ve raro, simplemente es que en Opera (el navegador que yo uso) es mucho más claro. El error se "soluciona" pasando el ratón por encima del botón, pero debería mostrarse bien siempre.

**Comment by erosguerrero** [comment]
O cambiando la imagen, que por el momento es una cuestión de diseño "visual" y no de código.

**Comment by Lurngi** [comment]
Queda pendiente para el futuro, cierro tarea
