### ISSUE TITLE
Memoria: correcciones capítulo 5

### ISSUE THREAD

**Issue by crisselene** [NILGroup/TFG-22-23-Recuerdame2.0#457]
- [x] Figura 5.1.
- [x] 5.1.4.1 Cambios de colores
- [x] 5.1.4.3 Patrones de diseño
- [x] 5.1.5 Aplicación _responsive_
- [x] 5.1.6 Observaciones
- [x] 5.2.5 Incorporación de ficheros a los informes
- [x] Intro 5.3. Nuevas funcionalidades
- [x] 5.3.1 Ventanas emergentes
- [x] 5.3.2 Diagnóstico inicial (falta lo de que explicamos el gráfico con más detalles en el 5.3.7)
- [x] 5.3.3 Repetir sesiones
- [x] 5.3.4 Buscadores
- [x] 5.3.5 Notificaciones y evitación de errores
- [x] 5.3.6 Tooltips
- [x] 5.3.7 Gráficas para mostrar la evolución del paciente
- [x] 5.3.8 Resúmenes de historia de vida (lo hace Sergio)
- [x] 5.3.9 Vídeos de historia de vida
- [x] 5.4 Servidor

**Comment by erosguerrero** [comment]
Graficas 5.3.7 deberia moverse a diagnostico inicial
