### ISSUE TITLE
Código: Modificar Front End

### ISSUE THREAD

**Issue by Lurngi** [NILGroup/TFG-22-23-Recuerdame2.0#46]

**Comment by erosguerrero** [comment]
He modificado el Front End de la aplicación, colores, tamaños, botones, logo... Hay tareas más especificas de zonas, pero esta incluye el refactor general de la personalidad de la App (I guess)

**Comment by erosguerrero** [comment]
![Image](https://user-images.githubusercontent.com/94256335/198049625-2dedd551-1008-492c-8d49-aff203fbfabd.png)
