### ISSUE TITLE
Memoria: 4. Creación de tablero Kaban y definición de políticas

### ISSUE THREAD

**Issue by erosguerrero** [NILGroup/TFG-22-23-Recuerdame2.0#5]
Es necesario establecer las políticas explícitas de Kanban, crear el tablero en el proyecto de GitHub y documentarlo en la memoria

**Comment by Lurngi** [comment]
He hecho los cambios pertinentes a las columnas y politicas tras la revisión de Virginia, queda documentarlo en la memoria

**Comment by crisselene** [comment]
añadidos los índices de la memoria para cada issue de redacción de memoria

**Comment by crisselene** [comment]
cambio de issues generales a issues más específicas

**Comment by Lurngi** [comment]
Falta añadir en memoria el WIP
