### ISSUE TITLE
Código: Frontend, formularios

### ISSUE THREAD

**Issue by crisselene** [NILGroup/TFG-22-23-Recuerdame2.0#50]

**Comment by erosguerrero** [comment]
Los formularios quedarían tal que así. Si quieres que tengan algún fondo igual, o algún cambio así decidme. Pero en principio se quedan así por este hito.


![Image](https://user-images.githubusercontent.com/94256335/198051526-d512ad9c-b3a1-4a70-a2c7-4a811038b5df.png)
