### ISSUE TITLE
Código: Frontend, navBar

### ISSUE THREAD

**Issue by crisselene** [NILGroup/TFG-22-23-Recuerdame2.0#51]

**Comment by crisselene** [comment]
no funciona el botón de cerrar sesión en algunas vistas

**Comment by erosguerrero** [comment]
El botón de cerrar sesión es del header

**Comment by Lurngi** [comment]
El botón de cerrar sesión no forma parte de esta tarea. Aun así a mi me funciona perfectamente, si el error persiste hay que abrir una nueva issue para investigarlo
