### ISSUE TITLE
Codigo: Organizador y buscador de las tablas

### ISSUE THREAD

**Issue by Lurngi** [NILGroup/TFG-22-23-Recuerdame2.0#58]

**Comment by crisselene** [comment]
![Image](https://user-images.githubusercontent.com/35759827/199296219-e9b0ef97-09d9-4222-8639-3838d1c7b56f.png)

en sesiones no se puede buscar en la tabla de recuerdos

**Comment by Lurngi** [comment]
En principio está corregido, tambien he conseguido colocar un poco mejor la barra de busqueda de las tablas

**Comment by Lurngi** [comment]
@PabloMartinez01 @erosguerrero eso es cosa vuestra, que como estáis trabajando en esas vistas he preferido no tocar

**Comment by erosguerrero** [comment]
@Lurngi Ya puedes tocar en recuerdo

**Comment by Lurngi** [comment]
Hecho
