### ISSUE TITLE
Código: Sesiones, modificación evaluación

### ISSUE THREAD

**Issue by crisselene** [NILGroup/TFG-22-23-Recuerdame2.0#62]
- [x] Añadir un botón de crear informe de sesión en la lista de sesiones en la columna de “finalizada/no finalizada” en caso de que no este finalizada la sesión, ya que es poco intuitivo el icono para finalizar la sesión que hay ahora mismo.
- [x] Los apartados de  “barreras” y “facilitadores” deben aparecer al finalizar una sesión y no al crearla.

**Comment by erosguerrero** [comment]
¿Aparecen los datos barreras y facilitadores en una sesión terminada?

**Comment by erosguerrero** [comment]
Lo del PDF muy top, por mi parte

**Comment by Lurngi** [comment]
Lo de barreras y facilitadores es una tarea de la Issue de informe de sesión que está actualmente en desarrollo
