### ISSUE TITLE
Código: Informes de sesión, modificación evaluación

### ISSUE THREAD

**Issue by crisselene** [NILGroup/TFG-22-23-Recuerdame2.0#63]
- [x] Los informes deberían estar en la sección de “Sesiones” y no en “Evaluaciones”. 
- [x] Eliminar el atributo “fecha informe”, ya que resulta redundante, pues lo habitual es hacer el informe justo al finalizar la sesión. 
- [x] Al generar el pdf del informe de sesión se deben añadir las observaciones. 
- [x] En el informe de sesión añadir un atributo que indique si es o no adecuado seguir con este tipo de terapias.  (Eran los recuerdos, estaba mal en la memoria de R1)
- [x] Añadir tanto en el informe de sesión como en el PDF generado los recuerdos utilizados en la sesión. (Movido a nueva Issue)
- [x] Añadir la duración de la sesión 
- [x] Añadir la hora en la que se realizó la sesión.

**Comment by crisselene** [comment]
**2º punto**: no entiendo bien el segundo punto de eliminar la fecha del informe, puesto que en nuestro listado de informes sigue apareciendo la fecha, ¿es de informes de seguimiento o de sesión?, ¿tal vez debería ser fecha de sesión? no acabo de entender por qué resulta redundante y cuál ha sido el cambio :

![Image](https://user-images.githubusercontent.com/35759827/200170041-30ab7b0f-ce1a-4a8a-8d87-d3b8cceafaf8.png)

![Image](https://user-images.githubusercontent.com/35759827/200169949-0af0af3d-7762-41b8-8458-ad0ea0479c39.png)

** 5º punto:**  ¿Dónde se ha añadido en el pdf los recuerdos, y en la página? No los he encontrado:


![Image](https://user-images.githubusercontent.com/35759827/200170316-cfbef708-449c-4827-b00d-0d418d80216f.png)


![Image](https://user-images.githubusercontent.com/35759827/200170327-7fd7fcc1-bd35-41e1-91a7-b44afbc8aed3.png)

**6º punto:** que no aparezca la duración de la sesión en el pdf no sé si es correcto.

**El resto correcto.**

**Comment by Lurngi** [comment]
Estás mirando los informes de seguimiento, no los de sesión.
Los informes de sesión se generan al cerrar una sesión

**Comment by crisselene** [comment]
el segundo punto me sigue generando duda porque pone que no pongamos fecha del informe pero sigue apareciendo en nuestra aplicación. habrá que tratar esta tarea en una daily

**Comment by crisselene** [comment]
la fecha sale con una T, no sé si es en esta tarea pero es que no sé donde quiere que lo escriba Adri T-T

**Comment by SerArias** [comment]
- En el pdf generado no se muestra en ningún lado si se debe seguir con este tipo de terapias (aunque sí se da la opción en Generar Informe de Sesión).

- En el pdf generado no se muestra en ningún lado la duración de la sesión (aunque sí se da la opción en Generar Informe de Sesión).

**Comment by crisselene** [comment]
hecho 👍

**Comment by PabloMartinez01** [comment]
No veo hecho el punto 4, aunque me suena que lo cambiamos a los recuerdos o algo así

**Comment by Lurngi** [comment]
Exacto, era cosa de los recuerdos y estaba mal en la memoria de Recuérdame 1
