### ISSUE TITLE
Código: Informes de seguimiento, modificación evaluación

### ISSUE THREAD

**Issue by crisselene** [NILGroup/TFG-22-23-Recuerdame2.0#64]
- [x] Añadir el numero de sesiones realizadas desde el ultimo informe de seguimiento.

**Comment by erosguerrero** [comment]
![Image](https://user-images.githubusercontent.com/94256335/200089489-cb6ba970-3ad5-4243-bf4e-fa771b3862f9.png)

Creo que informe es ambiguo y debería especificar entre informe de sesiones e informes de seguimiento

**Comment by crisselene** [comment]
por mi, está bien

**Comment by Lurngi** [comment]
He implementado el cambio
