### ISSUE TITLE
Código: Personas relacionadas, modificación evaluación

### ISSUE THREAD

**Issue by crisselene** [NILGroup/TFG-22-23-Recuerdame2.0#66]
- [x] Añadir localidad o residencia, un campo para observaciones e indicar el nivel de contacto con el paciente.
- [x] En tipo de relación dar la opción de añadir un tipo de relación que no aparezca en el despegable.

**Comment by Lurngi** [comment]
- Faltan placeholders
- Se puede guardar una persona relacionada con un email con formato inválido
- El botón de eliminar de la vista de showByPaciente no pide confirmación antes de borrar
