### ISSUE TITLE
Código: Calendario, modificación evaluación

### ISSUE THREAD

**Issue by crisselene** [NILGroup/TFG-22-23-Recuerdame2.0#67]
- [x] Añadir en el calendario las sesiones del terapeuta. Cuando el terapeuta cree una sesión debe aparecer en el calendario automáti-
camente.
- [x] Al añadir un nuevo evento en el calendario que pueda ser tanto una actividad del cuidador como una sesión del terapeuta.
- [x] Al crear una actividad, cambiar el campo “observaciones” por “pautas sencillas”. Este campo deber servir para indicar al cui-
dador los pasos que debe seguir para realizar la actividad.
- [x] Check color opcional [44:30], tener en cuenta el color de las letras sobre el fondo
- [x] Filtros entre deberes o sesiones. Y que al cuidador *solo* se le muestra los deberes. [50]
- [x] Arreglar hora
- [x] Sincronizar las sesiones aparezcan en el calendario [56]
- [x] Que se pueda crear una sesión
- [x] Cambiar observaciones por Pautas para el cuidador
- [x] Cuidador: Poder marcar  tareas como hecho en el calendario, y una vez hecha, un campo de como ha ido
- [x] Empezar en lunes en vez de en domingo
- [x] Hay filas de más

**Comment by erosguerrero** [comment]
![Image](https://user-images.githubusercontent.com/94256335/217801561-b8963f2c-2ca7-4ad9-87b3-a0faf5d223d8.png)

**Comment by erosguerrero** [comment]
![Image](https://user-images.githubusercontent.com/94256335/217801925-d05c3493-d47b-458f-8a6d-b20e8f8de9dd.png)

**Comment by erosguerrero** [comment]
Tengo alguna duda de interfaz. Pero la funcionalidad está probada.

**Comment by crisselene** [comment]
traducir:
![Image](https://user-images.githubusercontent.com/35759827/218126149-d438ec7d-6744-4723-9e0f-9a0c8d8436d8.png)
