### ISSUE TITLE
Código: Pacientes, modificación evaluación

### ISSUE THREAD

**Issue by crisselene** [NILGroup/TFG-22-23-Recuerdame2.0#68]
- [x] Al añadir un nuevo paciente en tipo de residencia añadir un desplegable con vivienda unifamiliar, piso, residencia de mayores, centro de día y otros. 
- [x] Cambiar el campo “residencia actual” por “dirección del domicilio”. 

- [x] Añadir la ocupación laboral principal, el estado civil, hijos, nivel de estudios con desplegable, antigüedad en el centro, el diagnóstico inicial y una foto del paciente.

- [x] Dar la opción de añadir más de un cuidador a un paciente.

- [x] A la hora de ver los datos del paciente que aparezca el listado de los informes de seguimiento para ver el progreso y la lista de personas relacionadas.

**Comment by Lurngi** [comment]
No sé a qué se refiere con "Hijos", en el tercer checkbox de esta Issue. Necesitaríamos los videos

**Comment by crisselene** [comment]
![Image](https://user-images.githubusercontent.com/35759827/199293605-94cf00de-f6a5-43a5-9856-994014795cde.png)
Si se les puede meter margen sería perfecto. 
Además el buscador se sale de la caja por un pelín:


![Image](https://user-images.githubusercontent.com/35759827/199293775-307c1a23-add5-486c-947b-d7202d765f8f.png)

**Comment by Lurngi** [comment]
Hecho :)

**Comment by erosguerrero** [comment]
Añadir número de hijos

**Comment by Lurngi** [comment]
Botón otro
