### ISSUE TITLE
Código: Crear cuidador, modificación evaluación

### ISSUE THREAD

**Issue by crisselene** [NILGroup/TFG-22-23-Recuerdame2.0#69]
- [x] Añadir teléfono, localidad de residencia y grado de parentesco.
- [x] Eliminar el nombre de usuario les resultaba confuso y poco útil.

**Comment by erosguerrero** [comment]
Se han quitado los "..." para quitar dramatismo

**Comment by erosguerrero** [comment]
Actualizada la vista de crear y mostrar cuidador

**Comment by erosguerrero** [comment]
Parentesco hecho bajo esta fuente: 

![Image](https://user-images.githubusercontent.com/94256335/200085020-651fcd41-793b-45af-9560-68fed0757bae.png)

wikipedia: https://es.wikipedia.org/wiki/Grado_de_parentesco

**Comment by Lurngi** [comment]
Yo dejaría los "...", hay que discutirlo en la siguiente reunión y unificar todas las vistas.
Lo de los grados de parentesco es algo que debemos hablar con los terapeutas, que sabrán darnos una mejor explicación de lo que desean. Por el momento, como ya hemos discutido, está bien así y en caso de tener que modificarlo es un esfuerzo mínimo.
El resto perfe, dejo mi like

**Comment by erosguerrero** [comment]
Los "..." no está en ninguna de mis vistas por lo tanto queda unido, anyways es estético.
Y exacto, el grado ya se hablará de momento se cierra como realizado.
