### ISSUE TITLE
Código: Navbar, modificación evaluación

### ISSUE THREAD

**Issue by crisselene** [NILGroup/TFG-22-23-Recuerdame2.0#70]
- [x] Añadir en el menú, una pestaña para ver la lista de cuidadores de un paciente.
- [x] Quitar la pestaña de paciente del menú y poder acceder a los datos del paciente pinchando en su nombre.

**Comment by Lurngi** [comment]
Se ha comentado cambiar el color del enlace al perfil del paciente. Por el momento se queda así, pendiente de la evaluación de los terapeutas
