### ISSUE TITLE
Memoria: Correcciones

### ISSUE THREAD

**Issue by crisselene** [NILGroup/TFG-22-23-Recuerdame2.0#72]
- [x] Eros
- [x] Adri
- [x] Cris
- [x] Sergio
- [x] Pablo

**Comment by Lurngi** [comment]
Como comenté, hice las correcciones de la memoria que envió Virginia hasta el punto 5 (no incluido). Falta terminar las de Virginia y hacer las de Susana

**Comment by crisselene** [comment]
se ha realizado:

- reescritura del punto 1.2 y añadir la motivación del TFG

**Comment by crisselene** [comment]
- eliminado el párrafo de fallos en las vistas(5.1.3), para abordar el tema en las observaciones totalmente(5.1.4)
- añadido fallo del cálculo de edades en el apartado 5.1.4
