### ISSUE TITLE
Memoria: Retrospectiva

### ISSUE THREAD

**Issue by crisselene** [NILGroup/TFG-22-23-Recuerdame2.0#73]

**Comment by erosguerrero** [comment]
El doble espaciado no sé si es correcto



![Image](https://user-images.githubusercontent.com/94256335/200086598-44d56c78-5320-46b1-954b-bdf44560a6d7.png)

**Comment by Lurngi** [comment]
La imagen de la retrospectiva no debería estar tumbada y queda muy mal en la memoria.
Falta el apartado 4.1.3 dónde hay que explicar qué son y para qué sirven este tipo de reuniones, ya que no debería estar dentro del texto de la primera reunión (Ya he borrado ese párrafo de una única linea)
El resto perfecto, he corregido algunas erratas y ampliado el léxico con sinónimos

**Comment by crisselene** [comment]
la imagen ladeada fue cómo nos explicó Virginia que aplicáramos los anexos que no se vieran bien.

**Comment by crisselene** [comment]
Igualmente podrías no haber borrado la información si no que ponerla arriba para que se amplie :)

**Comment by crisselene** [comment]
hecha la introducción de reuniones de retrospectiva.
