### ISSUE TITLE
Código: Recuerdos, revisión vídeos terapeutas

### ISSUE THREAD

**Issue by Lurngi** [NILGroup/TFG-22-23-Recuerdame2.0#78]
- [x] La etiqueta emoción es confusa se debe definir definir mejor. "Emocion producida"

- [x] En el campo puntuación no queda clara cual es la escala, se debería poner los números del 1 al 10 e incluso acompañar de emoticonos a los extremos.

- [x] Categoría OTRO, poder añadirlo como en persona relacionada

**Comment by erosguerrero** [comment]
Ponía Recuerdo, pero son tareas de sesiones

**Comment by Lurngi** [comment]
De hecho, es de Recuerdo, no hay nada relacionado con Sesión, más bien con Informe de Sesión, y sigue siendo exclusivamente con la vista de estos

**Comment by erosguerrero** [comment]
Hecho 1 y 2.

**Comment by Lurngi** [comment]
La barra de puntuacion no es responsive, dale una vuelta. Intenta ponerle medida vw o %

**Comment by Lurngi** [comment]
Estos 2 selects salen cortados

![Image](https://user-images.githubusercontent.com/72133257/216769363-c1d895f1-8383-413b-ba60-d7ff0792254d.png)

**Comment by crisselene** [comment]
lo de que salgan cortados era cuestión de diseño, creo que ya está solucionado ero si veis más cosas avisadme en la tarea de estilo porque hay tropecientas cosillas que se me han podido escapar

**Comment by crisselene** [comment]
ah, y la barra de puntuación se ha hecho lo que se ha podido, es una locura de vista xd
