### ISSUE TITLE
Memoria: 4.1.3. Reuniones de retrospectiva

### ISSUE THREAD

**Issue by Lurngi** [NILGroup/TFG-22-23-Recuerdame2.0#82]

**Comment by Lurngi** [comment]
Algunas cosillas corregidas, e igual el último párrafo es un poco confuso. Creo que haría falta redactarlo de nuevo, aunque yo esperaría a las correcciones de Virginia. Por el momento dejo mi like

**Comment by SerArias** [comment]
Tan solo he modificado un par de cosas. Creo que todo queda bastante claro
