### ISSUE TITLE
Memoria: 5.2.1 Rediseño

### ISSUE THREAD

**Issue by Lurngi** [NILGroup/TFG-22-23-Recuerdame2.0#85]

**Comment by erosguerrero** [comment]
Tremendo párrafo lleno de imágenes, pido perdón.

**Comment by crisselene** [comment]
corregido error con la cursiva en "placeholders". Las imágenes en principio están correctamente colocadas.

**Comment by SerArias** [comment]
Modificadas algunas líneas que, a mi parecer, resultaban confusas. Coincido en que las imágenes están colocadas correctamente
