### ISSUE TITLE
Memoria: 5.2.2 Ventanas emergentes

### ISSUE THREAD

**Issue by Lurngi** [NILGroup/TFG-22-23-Recuerdame2.0#86]

**Comment by erosguerrero** [comment]
Modales nuevos en sesion y recuerdo

**Comment by Lurngi** [comment]
Falta añadir cómo funcionan los modales indexados porque bootstrap no los incluye

**Comment by Lurngi** [comment]
Repensaría la organización de este apartado en la siguiente reunión

**Comment by Lurngi** [comment]
Falta añadir la imagen del modal baby

**Comment by crisselene** [comment]
corregidos errores sintácticos hasta ahora. Faltan cosas... ?

**Comment by Lurngi** [comment]
He reescrito la gran mayoría del apartado para que quede claro cual era el problema de Recuérdame 1.0 y cómo hemos decidido solucionarlo, así como explicar un poco más esta última parte

**Comment by SerArias** [comment]
Corregidos algunos errores de cohesión y gramaticales
