### ISSUE TITLE
Código: Corregir modal Sesión

### ISSUE THREAD

**Issue by Lurngi** [NILGroup/TFG-22-23-Recuerdame2.0#88]

**Comment by PabloMartinez01** [comment]
En una primera revisión se me ha duplicado un recuerdo al crearlo en el modal. Luego he reiniciado todo y ya no me ha vuelto a fallar. Los modales funcionan bien

**Comment by crisselene** [comment]
en crear sesión, si intentas añadir un recuerdo y SIN RELLENAR NADA das a guardar, y seguidamente refrescas la página aparece esto:


![Image](https://user-images.githubusercontent.com/35759827/215342249-551aad6e-8133-4685-b0e6-14e282151c5a.png)

**Comment by crisselene** [comment]
En el modal de sesión, cuando quieres añadir una persona relacionada nueva que aparece otro modal, no te deja guardar con los campos marcados con asteriscos vacíos pero no te indica ningún error 



![Image](https://user-images.githubusercontent.com/35759827/215343428-172b5bbd-cb2b-4fd7-9b51-8ee2fb531f48.png)

**Comment by SerArias** [comment]
- En el modal de "Crear: Personas relacionadas", no se comprueba que el teléfono introducido de persona relacionada sea del formato correcto, y lo guarda igualmente en la base de datos.

![Image](https://user-images.githubusercontent.com/99254373/216091123-b7788a77-5cf1-4e06-bd9f-fbf4bb5abeef.png)

- Al pulsar sobre el botón de "Añadir existente" al listado de personas relacionadas no aparece el botón para seleccionarlo.

![Image](https://user-images.githubusercontent.com/99254373/216092867-e69b0d07-69d1-46bb-a5d8-caf47849462f.png)

Además, si creo una nueva persona relacionada y posteriormente le doy a "Añadir existente", la tabla se deforma por completo.

![Image](https://user-images.githubusercontent.com/99254373/216093568-e34e3159-3547-497e-9b90-99829836f377.png)

Por otro lado, cuando se añade una persona relacionada al listado de personas relacionadas, tampoco se muestra la tabla como debería.

![Image](https://user-images.githubusercontent.com/99254373/216093923-3d8fdc7c-7e40-4808-b72b-e4e5c6fc0e32.png)

- Al crear un nuevo recuerdo, si se pulsa sobre "Guardar" sin haber completado todos los campos, no hace absolutamente nada.

- Al añadir un nuevo recuerdo, la tabla no se muestra como debería, pues de nuevo los atributos del recuerdo no se corresponde con los nombres de las columnas. Además, el texto "No hay datos disponibles" se mantiene.

![Image](https://user-images.githubusercontent.com/99254373/216094775-0698d7c1-3739-4a36-8bd3-c810358330de.png)

**Comment by Lurngi** [comment]
En principio he arreglado el error de "No hay datos disponibles" y lo de que las tablas no se vean bien. Queda pendiente mirar las validaciones que le corresponden a @PabloMartinez01

**Comment by PabloMartinez01** [comment]
Hecho y ahora ya funciona bien y se añaden bien las rows a las datatables
