### ISSUE TITLE
Investigación: Cambios vídeo Iván

### ISSUE THREAD

**Issue by erosguerrero** [NILGroup/TFG-22-23-Recuerdame2.0#95]

**Comment by crisselene** [comment]
- cuidado con los ejemplos que pongamos, por ejemplo, el recuerdo de un casamiento es el recuerdo de la boda, no del matrimonio que es un concepto muy general.
- poner la escala en el recuerdo (ya está hecho creo), no queda claro qué puntuación indica esta escala ¿es el grado de que está el recuerdo de perder? ?O es el grado de emoción? ¿o grado de positividad o negatividad? genera dudas. Indicar de qué es la puntuación. Sugiere añadir unos iconos con caritas tristes o felies, le resultaría más intuitivo, y con colores rojos para lo triste y lo alegre verde.
- fecha del informe es redundante al ver un informe de sesión. (creo que ya está hecho)
- en el pdf de seguimiento imprimir el diagnóstico y también las observaciones
- poder seleccionar más de una etapa, etiqueta... multifiltro (ya está)
- en el pdf de hitoria de vida poner una fotografía actual del paciente
- evitar espacios en blanco entre fotos y las fotos grandes (creo que ya está pero se podría mejorar poniendo las imágenes en fila en vez de en columna)
- el formato de la fecha en el pdf de historia de vida debería ser "día de mes de año" (escrito, 3 de febrero de 1940)
- cambiar el page del pdf a "página" (ya está hecho)
- en el listado de recuerdos sugiere que entre paréntesis se ponga que es de mayor a menor antiguedad, y poder ordenarlo como él quiera por la columna que quiere, también añadir un buscador
- las fotos cuando se cliquen deben ampliarse considerablemente, cuanto más grande mejor
- en personas realcionadas falta información, como localidad de residencia por si coincide con la de la persona de la terapia, incluir un campo de observaciones para añadir otros aspectos como la relación con esa persona
- añadir en personas relacionadas con qué persona tiene más relación, quién es la persona de contacto principal, prsona de contacto principal
- en el calendario, si la herramienta no tiene definido unos colores (como por ejemplo, el rojo para lo urgente, etc.) entonces puede ser confuso ponerle colores a los eventos porque para cada terapeuta puede significar cosas distintas y despista. Habría que dar la opción de no poner color por si no son necesarios.
- en el calendario le gusta lo de dar doble click en el día y puedas añadir un evento
- el calendario debe poderse diferenciar las actividades que se mandan "para casa" y las sesiones que se quiera organizar o planificar el terapeuta. Él propone tener dos calendarios distintos y virginia propone poner un filtro entre actividades. Poner de qué terapeuta es el evento.
- al crear una sesión, debería poderse añadir un título que sea el que aparezca en el calendario para terapeutas.
-  en el calendario de terapeutas al darle al "+" le lleve a añadir una sesión, y en el calendario para cuidadores le aparezca para crear una actividad y añadirle un campo de pautas para que las siga el cuidador, y se podría llamar indicaciones para el cuidador.
- barreras y facilitadores no debería estar en crear sesión si no en el informe de lasesión a posteriori. También el riesgo de perder el recuerdo(estado),etiqueta, la puntuación. Añadir también el listado de los recuerdos para poder editarlos. Es decir, para la creación de sesión los campos que dejaría es el nombre, la fecha, la etapa de vida y la categoría. Para generar el informe de la sesión se deben añadir los campos de estado , etiqueta, la puntuación y la emoción y quitarlo de crear sesión.
- los botones para atrás no deberían borrar los campos ya añadidos 
- columna para crear informe, porque es importante generar una sesión. (creo que ya está)
-  el termino de sesión finalizada o no le resulta confuso porque no sabe si es finalizar la sesión o finalizar de hacer el informe, él propone mejor ponerle un estado o poner un botón que sea generar informe, es decir, que se sepa si se ha generado el informe o no en vez de poner finalizado o no.
- tipo de residencia a la hora de crear un paciente con un desplegable (creo que ya está hecho)
- en la creación de paciente le parece ambiguo poner residencia actual, él pondría dirección de residencia
- lo del icono del ojo le parece confuso
- para ver el paciente le parece importante añadir el estado civil y el puesto de trabajo principal. Hijos, si tiene o no, nivel de estudios, antiguedad en el centro y diagnóstico principal(es decir, una parte clínica) que se pueda actualizar con el último informe de esa persona, el último diagnóstico. Es decir, que se vaya actualizando la información con los últimos informes. También que aparezca el primer diagnóstico y también puedas acceder desde aquí, a los informes de seguimiento del paciente. Además dice que nada más crear un paciente poder añadir un informe de seguimiento pero que no se llame así, que se llame añadir informe inicial, para añdir la primera información del paciente.
- nombre de usuario del cuidador sobra (creo que ya está), y añadir el teléfono del cuidador, y localidad de residencia y el parentesco.
- un paciente puede tener varios cuidadores, añadir un listado de cuidadores del paciente que debería añadir en la ficha de paciente y una opción de ver los cuidadores
-  en el menú, clicando en la foto del paciente o en su nombre acceder a la ficha de la persona
- en la ficha del paciente añadir poder ver las personas relacionadas
- en el menú, poner un acceso directo al cuidador, al lado de calendario
-  cuando entra como cuidador, la palabra paciente le suena demasiado hospitalario, él pondría persona atendida (DIRECTAMENTE QUITARLO Y PODER VER LA INFO DEL PACIENTE CLICNADO EN SU NOMBRE A LA DERECHA) 
-  como cuidador, cuando ves un recuerdo, no debería aparecer es estado, la etiqueta, la puntuación y la emoción
-  en cuidador, cree que falta un aviso de tarea pendiente que le puso el terapeuta y que pueda marcar que ha hecho la tarea y poder poner un campo de cómo ha ido la tarea
-  para cuidadores, al entrar en la applicación que salga mejor antes el calendario, que la pantalla de inicio no sea la información del paciente o incluso un listado de tareas pendientes
-  para el cuidador, propone una pantalla donde aparezca un carrusel solo con las imágenes para que lo vean fácilmente para usarlo, de manera que puedan acceder fácilmente
