### ISSUE TITLE
Investigación: Cambios vídeo Adriana

### ISSUE THREAD

**Issue by erosguerrero** [NILGroup/TFG-22-23-Recuerdame2.0#96]

**Comment by Lurngi** [comment]
Definir escala 16:40

Informes de sesión mal colocado 22:50

Barreras y facilitadores deben estar TAMBIEN en el informe de sesión (implícito con lo anterior)

Continuar con este tipo de sesión (en realidad se refiere a los recuerdos de la sesión, aclarandolo en el min 28:50) 23:20

En cada sesión trabajar con hasta 3 recuerdos (aunque no queda claro si se puede trabajar con más) 25:10

Al rellenar los informes de sesión se debe marcar si se puede continuar usando o no un recuerdo (28:50)

En informe de sesión mostrar los recuerdos y si deben continuar usandose o no (30:00)

Sesiones realizadas entre cada evaluación (añadirlo en la tabla, vista y PDF de la evaluación) 32:20

Duración ESTIMADA de la sesión (34:30)
Hora de inicio y fin de una sesión?? (Lo dice muy por encima y no queda claro) 36:50

En Recuérdame 1 la fecha de fin de una historia de vida es la fecha actual (al menos en el vídeo) 43:00

Mostrar la fecha de creación de todos los PDF 44:50

Otros (e igual añadir la opción de terapeuta y cuidador, aunque mejor Otros) y poder añadir una foto de la persona 50:00
