### ISSUE TITLE
Código: Vista NavBar, revisión vídeos terapeutas

### ISSUE THREAD

**Issue by erosguerrero** [NILGroup/TFG-22-23-Recuerdame2.0#98]
- [ ] Notificaciones de tareas pendientes del calendario

**Comment by erosguerrero** [comment]
Yo lo haría con las badges de boostrap https://getbootstrap.com/docs/4.0/components/badge/

**Comment by erosguerrero** [comment]
https://getbootstrap.com/docs/5.0/components/badge/

**Comment by Lurngi** [comment]
Outdated
